ZumZumFinancials_Dev1/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Nominal_Account__c</fullName>
        <label>Nominal Account</label>
        <referenceTo>Nominal_Account__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Tax_Rate__c</fullName>
        <label>Tax Rate</label>
        <referenceTo>Tax_Rate__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

ZumZumFinancials_Dev1/src/objects/Bank_Account__c.object
<CustomObject>
    <fields>
        <fullName>Nominal_Account__c</fullName>
        <label>Nominal Account</label>
        <referenceTo>Nominal_Account__c</referenceTo>
        <relationshipLabel>Bank Accounts</relationshipLabel>
        <relationshipName>Bank_Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Bank Account</label>
    <nameField>
        <label>Bank Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bank Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

ZumZumFinancials_Dev1/src/objects/Nominal_Account__c.object
<CustomObject>
    <fields>
        <fullName>Account_Code__c</fullName>
        <label>Account Code</label>
        <precision>4</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Expense__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Expense</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Nominal_Code__c</fullName>
        <formula>TEXT( Account_Code__c )</formula>
        <label>Nominal Code</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sub_Category__c</fullName>
        <label>Sub Category</label>
        <referenceTo>Sub_Category__c</referenceTo>
        <relationshipLabel>Nominal Accounts</relationshipLabel>
        <relationshipName>Nominal_Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Tax_Rate__c</fullName>
        <label>Tax Rate</label>
        <referenceTo>Tax_Rate__c</referenceTo>
        <relationshipLabel>Nominal Accounts</relationshipLabel>
        <relationshipName>Nominal_Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Nominal Account</label>
    <nameField>
        <label>Nominal Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Nominal Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

ZumZumFinancials_Dev1/src/objects/Nominal_Categories__c.object
<CustomObject>
    <label>Nominal Category</label>
    <nameField>
        <label>Nominal Categories Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Nominal Categories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

ZumZumFinancials_Dev1/src/objects/Recurring_Transaction__c.object
<CustomObject>
    <description>// Made by Fatima
used in Recurring page</description>
    <fields>
        <fullName>Nominal_Account__c</fullName>
        <label>Nominal Account</label>
        <referenceTo>Nominal_Account__c</referenceTo>
        <relationshipLabel>Recurring Transactions (Nominal Account)</relationshipLabel>
        <relationshipName>Recurring_Transactions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Transaction_Type__c</fullName>
        <label>Transaction Type</label>
        <picklist>
            <picklistValues>
                <fullName>BankCashCreditCardPayment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BankCashCreditCardReceipt</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BankCashCreditCardTransfer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CustomerPaymentonAccount</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>VAT__c</fullName>
        <label>VAT</label>
        <referenceTo>Tax_Rate__c</referenceTo>
        <relationshipLabel>Recurring Transactions</relationshipLabel>
        <relationshipName>Recurring_Transactions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Vat_Amount__c</fullName>
        <label>Vat Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Recurring Transaction</label>
    <nameField>
        <label>Recurring Transactions Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Recurring Transactions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

ZumZumFinancials_Dev1/src/objects/Sub_Category__c.object
<CustomObject>
    <fields>
        <fullName>Nominal_Categories__c</fullName>
        <label>Nominal Categories</label>
        <referenceTo>Nominal_Categories__c</referenceTo>
        <relationshipLabel>Sub Category</relationshipLabel>
        <relationshipName>Sub_Category</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Range_From__c</fullName>
        <label>Range From</label>
        <precision>4</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Range_To__c</fullName>
        <label>Range To</label>
        <precision>4</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Sub Category</label>
    <nameField>
        <label>Sub Category Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sub Category</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

ZumZumFinancials_Dev1/src/objects/Tax_Rate__c.object
<CustomObject>
    <fields>
        <fullName>Tax_Rate__c</fullName>
        <label>Tax Rate</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <label>Tax</label>
    <nameField>
        <label>Tax Rate Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tax</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

ZumZumFinancials_Dev1/src/classes/controllerBankRecurringTransaction.cls
public class controllerBankRecurringTransaction {
	public Recurring_Transaction__c objectRecurringTransaction {get;set;}
	public List<Bank_Account__c> listBankAccount{get;set;}
	public List<Tax_Rate__c> listTaxRate{get;set;}
	public string idNom{get;set;}
	public string retURL{get;set;}
	public Map<string,Nominal_Account__c> mp {get;set;}
	public controllerBankRecurringTransaction()
	{
		retURL = 'https://'+apexPages.currentPage().getHeaders().get('Host')+'/apex/BankMenu';
		objectRecurringTransaction = new Recurring_Transaction__c(); 
		mp = new Map<string,Nominal_Account__c>([select id,Name from Nominal_Account__c limit 1000]); 		
	}
	public List<SelectOption> getBankAccount()
	{
		List<SelectOption> options = new List<SelectOption>();
		for(Bank_Account__c bnk : [select id, Name, Nominal_Account__r.Nominal_Code__c, Nominal_Account__c from Bank_Account__c limit 1000])
		{
			options.add(new SelectOption(bnk.id,bnk.Nominal_Account__r.Nominal_Code__c+'-'+bnk.Name));
		} 
		return options;
	}
	public List<SelectOption> getTaxRate()
	{
		List<SelectOption> options = new List<SelectOption>();
		for(Tax_Rate__c tx : [select id, Name, Tax_Rate__c from Tax_Rate__c limit 1000])
		{
			options.add(new SelectOption(tx.id,tx.Name));
		} 
		return options;
	}
	public PageReference Cancel()
	{
		return new PageReference(retURL);
	}
	public PageReference Save()
	{
		try
		{			
			if(mp.KeySet().contains(idNom))
			objectRecurringTransaction.Nominal_Account__c = mp.get(idNom).id;
			settingRules(); 					
			return null;
		}
		catch(exception e)
		{
			ApexPages.AddMessages(e);
			return null;
		}
	}
	public void settingRules()
	{
		if((objectRecurringTransaction.Transaction_Type__c == 'Bank/Cash/Credit Card Transfer') ||(objectRecurringTransaction.Transaction_Type__c == 'Customer payment on Account'))
		{		
			objectRecurringTransaction.VAT__c = null;
			objectRecurringTransaction.Vat_Amount__c = 0.0;			
		}		
	}
	private static testMethod void controllerBankRecurringTransaction_Test()
	{
		Tax_Rate__c tx = new Tax_Rate__c(Name = 'VAT' , Tax_Rate__c = 15 );
		insert tx ;
    	Nominal_Categories__c  nc = new Nominal_Categories__c (Name = 'this is test');
		insert nc ; 
		Sub_Category__c sb = new Sub_Category__c(Nominal_Categories__c = nc.Id , Range_To__c = 200, Range_From__c=10, Name = 'testSubcatagories');
		insert sb;
		Nominal_Account__c nm = new Nominal_Account__c (Sub_Category__c = sb.Id , Tax_Rate__c = tx.Id, Expense__c = true, Name = 'Plumbering', Account_Code__c = 1222);
		insert nm ;
		Nominal_Account__c nm1 = new Nominal_Account__c (Sub_Category__c = sb.Id , Tax_Rate__c = tx.Id, Expense__c = true, Name = 'Plumbering', Account_Code__c = 1299);
		insert nm1 ;
		Nominal_Account__c na = new Nominal_Account__c (Sub_Category__c = sb.Id , Tax_Rate__c = tx.Id, Expense__c = true, Name = 'Gardening', Account_Code__c = 100);
		insert na ;
		controllerBankRecurringTransaction recurTrans = new controllerBankRecurringTransaction();
		List<SelectOption> bnkAct = recurTrans.getBankAccount();
		List<SelectOption> txRat = recurTrans.getTaxRate();
		recurTrans.Cancel();
		recurTrans.Save();
	}	
}