ZumZumFinancials_Dev1/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Balance__c</fullName>
        <formula>Debit__c -  Credit__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Balance</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Nominal_Account__c</fullName>
        <label>Nominal Account</label>
        <referenceTo>Nominal_Account__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Tax_Rate__c</fullName>
        <label>Tax Rate</label>
        <referenceTo>Tax_Rate__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

ZumZumFinancials_Dev1/src/objects/Bank_Account__c.object
<CustomObject>
    <fields>
        <fullName>Account_Number__c</fullName>
        <externalId>true</externalId>
        <label>Account Number</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Nominal_Account__c</fullName>
        <label>Nominal Account</label>
        <referenceTo>Nominal_Account__c</referenceTo>
        <relationshipLabel>Bank Accounts</relationshipLabel>
        <relationshipName>Bank_Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Draft</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Deleted</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Bank Account</label>
    <nameField>
        <label>Bank Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bank Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

ZumZumFinancials_Dev1/src/objects/BankReconcile__c.object
<CustomObject>
    <fields>
        <fullName>Bank_Account__c</fullName>
        <label>Bank Account Name</label>
        <referenceTo>Bank_Account__c</referenceTo>
        <relationshipLabel>BankReconcile</relationshipLabel>
        <relationshipName>BankReconcile</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Charges_Amount__c</fullName>
        <label>Charges of Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Charges_Date__c</fullName>
        <label>Date of Charges</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Charges_Nominal_Account__c</fullName>
        <label>Nominal Account of Charges</label>
        <referenceTo>Nominal_Account__c</referenceTo>
        <relationshipLabel>BankReconcile (Charges Nominal Account)</relationshipLabel>
        <relationshipName>BankReconcile1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Ending_Balance__c</fullName>
        <label>Ending Balance</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Interest_Amount__c</fullName>
        <label>Interest of amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Interest_Date__c</fullName>
        <label>Date of Interest</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Interest_Nominal_Account__c</fullName>
        <label>Nominal Account of Interest</label>
        <referenceTo>Nominal_Account__c</referenceTo>
        <relationshipLabel>BankReconcile</relationshipLabel>
        <relationshipName>BankReconcile</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Reference__c</fullName>
        <label>Reference</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Statement_Date__c</fullName>
        <label>Statement Date</label>
        <type>Date</type>
    </fields>
    <label>BankReconcile</label>
    <nameField>
        <label>BankReconcile Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BankReconcile</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

ZumZumFinancials_Dev1/src/objects/Control_Account__c.object
<CustomObject>
    <fields>
        <fullName>Default_Bank__c</fullName>
        <label>Default Bank</label>
        <referenceTo>Nominal_Account__c</referenceTo>
        <relationshipLabel>Control Accounts (Default Bank)</relationshipLabel>
        <relationshipName>Default_Bank</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Nominal_Account__c</fullName>
        <label>Nominal Account</label>
        <referenceTo>Nominal_Account__c</referenceTo>
        <relationshipLabel>Control Accounts</relationshipLabel>
        <relationshipName>Control_Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Control Account</label>
    <nameField>
        <label>Control Accounts</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Control Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

ZumZumFinancials_Dev1/src/objects/Ledger__c.object
<CustomObject>
    <fields>
        <fullName>Bank_Reconcile_Date__c</fullName>
        <label>Bank Reconcile Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Bank_Reconcile__c</fullName>
        <label>Bank Reconcile</label>
        <length>1</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Reference__c</fullName>
        <label>Reference</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Tax_Rate__c</fullName>
        <label>Tax Rate</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Trans_Date__c</fullName>
        <label>Trans Date</label>
        <type>Date</type>
    </fields>
    <label>Ledger</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Ledger Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ledger</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

ZumZumFinancials_Dev1/src/objects/Nominal_Account__c.object
<CustomObject>
    <fields>
        <fullName>Account_Code__c</fullName>
        <label>Account Code</label>
        <precision>4</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Balance__c</fullName>
        <formula>Debit_Balance__c - Credit_Balance__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Balance</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Expense__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Expense</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Nominal_Code__c</fullName>
        <formula>TEXT( Account_Code__c )</formula>
        <label>Nominal Code</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sub_Category__c</fullName>
        <label>Sub Category</label>
        <referenceTo>Sub_Category__c</referenceTo>
        <relationshipLabel>Nominal Accounts</relationshipLabel>
        <relationshipName>Nominal_Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Tax_Rate__c</fullName>
        <label>Tax Rate</label>
        <referenceTo>Tax_Rate__c</referenceTo>
        <relationshipLabel>Nominal Accounts</relationshipLabel>
        <relationshipName>Nominal_Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Nominal Account</label>
    <nameField>
        <label>Nominal Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Nominal Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

ZumZumFinancials_Dev1/src/objects/Nominal_Categories__c.object
<CustomObject>
    <label>Nominal Category</label>
    <nameField>
        <label>Nominal Categories Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Nominal Categories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

ZumZumFinancials_Dev1/src/objects/Sub_Category__c.object
<CustomObject>
    <fields>
        <fullName>Nominal_Categories__c</fullName>
        <label>Nominal Categories</label>
        <referenceTo>Nominal_Categories__c</referenceTo>
        <relationshipLabel>Sub Category</relationshipLabel>
        <relationshipName>Sub_Category</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Range_From__c</fullName>
        <label>Range From</label>
        <precision>4</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Range_To__c</fullName>
        <label>Range To</label>
        <precision>4</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Sub Category</label>
    <nameField>
        <label>Sub Category Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sub Category</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

ZumZumFinancials_Dev1/src/objects/Tax_Rate__c.object
<CustomObject>
    <fields>
        <fullName>Tax_Rate__c</fullName>
        <label>Tax Rate</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <label>Tax</label>
    <nameField>
        <label>Tax Rate Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tax</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

ZumZumFinancials_Dev1/src/classes/controllerBankReconcileAccount.cls
public class controllerBankReconcileAccount {
	public BankReconcile__c objectBankReconcile{get;set;}	
	public BankReconcile__c curObjectBankReconcile{get;set;}			
	public Control_Account__c defaultBank{get;set;}
	public List<Ledger__c> financial{get;set;}	
	public string retURL {get;set;}
	public string idNom1{get;set;}
	public string idNom2{get;set;}
	public string BankId{get;set;}
	public decimal nomBalance{get;set;}
	public decimal Balance{get;set;}	
	public Bank_Account__c opt;
	
	public controllerBankReconcileAccount(ApexPages.standardController std) 
	{									
		objectBankReconcile = new BankReconcile__c();
		objectBankReconcile.Ending_Balance__c = 0.0;
		objectBankReconcile.Statement_Date__c = Date.today();
		retURL = 'https://'+apexPages.currentPage().getHeaders().get('Host')+'/apex/BankMenu';				
		defaultBank = [Select c.Default_Bank__r.Nominal_Code__c, c.Default_Bank__r.Name, c.Default_Bank__r.Id, c.Default_Bank__c From Control_Account__c c where c.Name= 'Control Accounts'];
		opt = [select Name, Nominal_Account__r.Id,Nominal_Account__r.Nominal_Code__c, Nominal_Account__r.Name from Bank_Account__c where Nominal_Account__r.id =: defaultBank.Default_Bank__r.id];		
		nomBalance = [Select Balance__c From Nominal_Account__c where id =: opt.Nominal_Account__r.Id].Balance__c;
		findBalance();
			
	}	
	public list<SelectOption> getBankAccount()//options from list of Bank Accounts with Nominal Codes
	{
		List<SelectOption> options = new list<SelectOption>();						
 		options.add(new SelectOption(opt.Nominal_Account__r.Id,opt.Nominal_Account__r.Nominal_Code__c+' - '+opt.Name));
		for(Bank_Account__c bnk : [select id, Name, Nominal_Account__r.Nominal_Code__c, Nominal_Account__c from Bank_Account__c where Status__c =: 'Active'])
		{			
			if(bnk.Nominal_Account__r.id != opt.Nominal_Account__r.Id)
				options.add(new SelectOption(bnk.Nominal_Account__r.Id ,bnk.Nominal_Account__r.Nominal_Code__c+' - '+bnk.Name));
		}
		return options;	
	}
	public void NominalBalance()
	{
		try
		{					
			nomBalance = [Select Balance__c From Nominal_Account__c where id =: BankId].Balance__c;
			findBalance();
		}
		catch(exception e)
		{
			apexpages.addmessages(e);
		}
	}		
	public void findBalance()
	{
		if(objectBankReconcile.Ending_Balance__c == null)
			objectBankReconcile.Ending_Balance__c = 0.0;
		if(objectBankReconcile.Interest_Amount__c == null)
			objectBankReconcile.Interest_Amount__c = 0.0;		
		if(objectBankReconcile.Charges_Amount__c == null)
			objectBankReconcile.Charges_Amount__c = 0.0;		
		decimal endBalance = nomBalance - objectBankReconcile.Ending_Balance__c;
		decimal intrst = endBalance + objectBankReconcile.Interest_Amount__c;
		balance =  intrst - objectBankReconcile.Charges_Amount__c;
				
	}
	public void SaveValidation()
	{
		if(objectBankReconcile.Ending_Balance__c == 0.0 || objectBankReconcile.Ending_Balance__c == null) 
			throw new CustomException('Enter Ending Balance first.');
		if(objectBankReconcile.Statement_Date__c == null)
			throw new CustomException('Enter Statement Date first.');
		if(objectBankReconcile.Interest_Amount__c != 0)
		{			
			if(objectBankReconcile.Interest_Date__c == null)
				throw new CustomException('Enter Interest Date first.');
			if(IdNom1 == null || IdNom1 == '')
				throw new CustomException('Select Nominal Account first under the head of Interest earned.');			
		}
		if(objectBankReconcile.Charges_Amount__c != 0)
		{			
			if(objectBankReconcile.Charges_Date__c == null)
				throw new CustomException('Enter Charges Date first.');
			if(IdNom2 == null || IdNom2 == '')
				throw new CustomException('Select Nominal Account first under the head of Amount Charges.');			
		}		
		if(((objectBankReconcile.Interest_Date__c != null) || (objectBankReconcile.Interest_Nominal_Account__c != null )) && ((objectBankReconcile.Interest_Amount__c <= 0) || (objectBankReconcile.Interest_Amount__c == null)))
			throw new CustomException('Enter Intrest Amount first.');
		if(((objectBankReconcile.Charges_Date__c != null) || (objectBankReconcile.Charges_Nominal_Account__c != null )) && ((objectBankReconcile.Charges_Amount__c <= 0) || (objectBankReconcile.Charges_Amount__c == null)))
			throw new CustomException('Enter Charges Amount first.');
		if(Balance != 0)
			throw new CustomException('Account is not balanced');
		if((IdNom1 != null && IdNom1 != '') || (IdNom2 != null && IdNom2 != ''))
			if((IdNom1 == idNom2) || (IdNom1 == BankId) || (BankId == idNom2))
				throw new CustomException('All three Nominals must be different');
		
	}
	public PageReference Save()
	{						
		try
		{							
			SaveValidation();
			if(idNom1 != null && idNom1 != '')				
				objectBankReconcile.Interest_Nominal_Account__c = idNom1;
			if(idNom2 != null && idNom2 != '')				
				objectBankReconcile.Charges_Nominal_Account__c = idNom2;
				
			Bank_Account__c bnkAcctt = [select id , Name from Bank_Account__c where Nominal_Account__r.Id =: BankId];									
			BankReconcileModel bnk = new BankReconcileModel(new BankReconcile__c(Bank_Account__c = bnkAcctt.id ,Reference__c = objectBankReconcile.Reference__c,Ending_Balance__c = objectBankReconcile.Ending_Balance__c,Statement_Date__c= objectBankReconcile.Statement_Date__c,Interest_Amount__c=objectBankReconcile.Interest_Amount__c,Interest_Date__c = objectBankReconcile.Interest_Date__c, Interest_Nominal_Account__c = objectBankReconcile.Interest_Nominal_Account__c ,Charges_Amount__c=objectBankReconcile.Charges_Amount__c, Charges_Date__c = objectBankReconcile.Charges_Date__c,Charges_Nominal_Account__c = objectBankReconcile.Charges_Nominal_Account__c)); 
			bnk.Save();	
			
			Ledger financials = new Ledger();				
			CustomerRefund_BudgetModel bModel = new CustomerRefund_BudgetModel();				
			if(objectBankReconcile.Interest_Nominal_Account__c != null )
			{			
				financials.AddBankReconcileTransaction(objectBankReconcile.Interest_Amount__c, objectBankReconcile.Ending_Balance__c, idNom1, BankId, objectBankReconcile.Reference__c, objectBankReconcile.Interest_Date__c, objectBankReconcile.Statement_Date__c);					
				bModel.AddDebit(idNom1,objectBankReconcile.Interest_Amount__c, string.valueOf(objectBankReconcile.Interest_Date__c));
	 			bModel.AddCredit(BankId, objectBankReconcile.Ending_Balance__c  , string.valueOf(objectBankReconcile.Statement_Date__c));
			}
			if(objectBankReconcile.Charges_Nominal_Account__c  != null )
			{		
				financials.AddBankReconcileTransaction(objectBankReconcile.Ending_Balance__c, objectBankReconcile.Charges_Amount__c, BankId, idNom2, objectBankReconcile.Reference__c, objectBankReconcile.Statement_Date__c, objectBankReconcile.Charges_Date__c);					
	 			bModel.AddDebit(BankId, objectBankReconcile.Ending_Balance__c , string.valueOf(objectBankReconcile.Statement_Date__c));
	 			bModel.AddCredit(idNom2,objectBankReconcile.Charges_Amount__c, string.valueOf(objectBankReconcile.Charges_Date__c)); 
			}									
			financials.save();				
			bModel.newSave();				
			financial = [select Trans_Date__c , Bank_Reconcile__c, Bank_Reconcile_Date__c from Ledger__c where Trans_Date__c <=: objectBankReconcile.Statement_Date__c];
			for (Ledger__c l : financial )
			{
				if(l.Bank_Reconcile__c == 'N')
				{
					l.Bank_Reconcile__c = 'Y';
					l.Bank_Reconcile_Date__c = Date.today();
				}
			}
			update financial;				
			return new PageReference('/'+bnk.curObjectBankReconcile.id);			
		}
		catch(exception e)
		{			 
			ApexPages.AddMessages(e);
			return null;
		}
	}		
	private static testMethod void controllerBankReconcileAccountTest()
	{
		Tax_Rate__c tx = new Tax_Rate__c(Name = 'VAT' , Tax_Rate__c = 15 );
		insert tx ;
    	Nominal_Categories__c  nc = new Nominal_Categories__c (Name = 'this is test');
		insert nc ; 
		Sub_Category__c sb = new Sub_Category__c(Nominal_Categories__c = nc.Id , Range_To__c = 200, Range_From__c=10, Name = 'testSubcatagories');
		insert sb;
		Nominal_Account__c nm = new Nominal_Account__c (Sub_Category__c = sb.Id , Tax_Rate__c = tx.Id, Expense__c = true, Name = 'Plumbering', Account_Code__c = 1222);
		insert nm ;
		Nominal_Account__c nm1 = new Nominal_Account__c (Sub_Category__c = sb.Id , Tax_Rate__c = tx.Id, Expense__c = true, Name = 'Plumbering', Account_Code__c = 1142);
		insert nm1 ;
		Nominal_Account__c nm2 = new Nominal_Account__c (Sub_Category__c = sb.Id , Tax_Rate__c = tx.Id, Expense__c = true, Name = 'Plumbering', Account_Code__c = 1500);
		insert nm2 ;
		Bank_Account__c ba = new Bank_Account__c (Nominal_Account__c = nm.id, Status__c = 'Active' , Name = 'Bank Receipt Account' , Account_Number__c = 'B745');
		insert ba;
		controllerBankReconcileAccount bnkReconcyl = new controllerBankReconcileAccount(new ApexPages.standardController(new BankReconcile__c()));
		bnkReconcyl.nomBalance = 10;		
		BankReconcile__c br = new BankReconcile__c(Bank_Account__c = ba.id ,Reference__c = 'testRefer',Ending_Balance__c = bnkReconcyl.nomBalance + 10 ,Statement_Date__c= Date.today() , Interest_Amount__c =  bnkReconcyl.nomBalance + 10 ,Interest_Date__c = Date.today() , Interest_Nominal_Account__c = nm1.id ,Charges_Amount__c= bnkReconcyl.nomBalance , Charges_Date__c = Date.today(),Charges_Nominal_Account__c = nm2.id);
		insert br;		
		List<SelectOption> bnkAcctt = bnkReconcyl.getBankAccount(); 
		bnkReconcyl.BankId = nm.id;
		bnkReconcyl.objectBankReconcile.Ending_Balance__c = null;
		bnkReconcyl.findBalance();
		try
		{
			bnkReconcyl.SaveValidation();
		}
		catch(exception e)
		{
			system.assertEquals(e.getMessage(), 'Enter Ending Balance first.');
		}
		bnkReconcyl.objectBankReconcile.Ending_Balance__c = 0;
		bnkReconcyl.findBalance();
		try
		{
			bnkReconcyl.SaveValidation();
		}
		catch(exception e)
		{
			system.assertEquals(e.getMessage(), 'Enter Ending Balance first.');
		}				
		bnkReconcyl.objectBankReconcile.Ending_Balance__c = bnkReconcyl.nomBalance - 1;
		bnkReconcyl.findBalance();
		try
		{
			bnkReconcyl.SaveValidation();
		}
		catch(exception e)
		{
			system.assertEquals(e.getMessage(), 'Account is not balanced');
		}
		bnkReconcyl.objectBankReconcile.Ending_Balance__c = bnkReconcyl.nomBalance + 10;
		bnkReconcyl.findBalance();
		bnkReconcyl.objectBankReconcile.Statement_Date__c = null;
		try
		{
			bnkReconcyl.SaveValidation();
		}
		catch(exception e)
		{
			system.assertEquals(e.getMessage(), 'Enter Statement Date first.');
		}	
		bnkReconcyl.objectBankReconcile.Statement_Date__c = Date.today();		
		bnkReconcyl.objectBankReconcile.Reference__c = 'test1';	
		bnkReconcyl.objectBankReconcile.Interest_Amount__c = bnkReconcyl.nomBalance + 10;	
		bnkReconcyl.objectBankReconcile.Interest_Date__c = null;
		bnkReconcyl.findBalance();
		bnkReconcyl.objectBankReconcile.Charges_Amount__c = bnkReconcyl.Balance;
		bnkReconcyl.findBalance();
		try
		{
			bnkReconcyl.SaveValidation();
		} 
		catch(exception e)
		{
			system.assertEquals(e.getMessage(), 'Enter Interest Date first.');
		}
		bnkReconcyl.objectBankReconcile.Interest_Date__c = Date.today();
		bnkReconcyl.findBalance();
		bnkReconcyl.idNom1 = null;
		try
		{
			bnkReconcyl.SaveValidation();
		}
		catch(exception e)
		{
			system.assertEquals(e.getMessage(), 'Select Nominal Account first under the head of Interest earned.');
		}		
		bnkReconcyl.objectBankReconcile.Interest_Nominal_Account__c = nm1.Id ;
		bnkReconcyl.idNom1 = nm1.Id; 
		bnkReconcyl.objectBankReconcile.Charges_Date__c = null;
		try
		{
			bnkReconcyl.SaveValidation();
		}
		catch(exception e)
		{ 
			system.assertEquals(e.getMessage(), 'Enter Charges Date first.');
		}
		bnkReconcyl.objectBankReconcile.Charges_Date__c = Date.today();
		bnkReconcyl.idNom2 = null;
		try
		{
			bnkReconcyl.SaveValidation();
		}
		catch(exception e)
		{
			system.assertEquals(e.getMessage(), 'Select Nominal Account first under the head of Amount Charges.');
		}	
		bnkReconcyl.objectBankReconcile.Interest_Nominal_Account__c = nm.Id ;
		bnkReconcyl.idNom2 = nm.id;
		try
		{
			bnkReconcyl.SaveValidation();
		}
		catch(exception e)
		{
			system.assertEquals(e.getMessage(), 'All three Nominals must be different');			
		}		
		bnkReconcyl.objectBankReconcile.Interest_Nominal_Account__c = nm2.Id ;
		bnkReconcyl.idNom2 = nm2.Id ;
		bnkReconcyl.save();
	}	  
}