ZumZumFinancials_Dev1/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Nominal_Account__c</fullName>
        <label>Nominal Account</label>
        <referenceTo>Nominal_Account__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Tax_Rate__c</fullName>
        <label>Tax Rate</label>
        <referenceTo>Tax_Rate__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

ZumZumFinancials_Dev1/src/objects/Activity_Code__c.object
<CustomObject>
    <fields>
        <fullName>Code__c</fullName>
        <label>Code</label>
        <length>10</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Activity Code</label>
    <nameField>
        <label>Activity Code Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Activity Codes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

ZumZumFinancials_Dev1/src/objects/Nominal_Account__c.object
<CustomObject>
    <fields>
        <fullName>Account_Code__c</fullName>
        <label>Account Code</label>
        <precision>4</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>S_O__c</fullName>
        <defaultValue>true</defaultValue>
        <label>S O</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Sub_Category__c</fullName>
        <label>Sub Category</label>
        <referenceTo>Sub_Category__c</referenceTo>
        <relationshipLabel>Nominal Accounts</relationshipLabel>
        <relationshipName>Nominal_Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Tax_Rate__c</fullName>
        <label>Tax Rate</label>
        <referenceTo>Tax_Rate__c</referenceTo>
        <relationshipLabel>Nominal Accounts</relationshipLabel>
        <relationshipName>Nominal_Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Nominal Account</label>
    <nameField>
        <label>Nominal Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Nominal Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

ZumZumFinancials_Dev1/src/objects/Nominal_Categories__c.object
<CustomObject>
    <label>Nominal Category</label>
    <nameField>
        <label>Nominal Categories Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Nominal Categories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

ZumZumFinancials_Dev1/src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Activity_End__c</fullName>
        <defaultValue>today()+365</defaultValue>
        <description>Expected activity end date, may post date eligibility end date</description>
        <inlineHelpText>Enter the expected activity end date, may post date eligibility end date</inlineHelpText>
        <label>Activity End</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Activity_Start__c</fullName>
        <defaultValue>today()</defaultValue>
        <description>Expected activity start date, may pre-date eligibility start date</description>
        <inlineHelpText>Enter the expected activity start date, may pre-date eligibility start date</inlineHelpText>
        <label>Activity Start</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Code__c</fullName>
        <description>Project code</description>
        <inlineHelpText>Enter a project code once activity has started on this opportunity/project</inlineHelpText>
        <label>Code</label>
        <length>20</length>
        <type>Text</type>
    </fields>
</CustomObject>

ZumZumFinancials_Dev1/src/objects/Sub_Category__c.object
<CustomObject>
    <fields>
        <fullName>Code__c</fullName>
        <label>Code</label>
        <length>50</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Nominal_Categories__c</fullName>
        <label>Nominal Categories</label>
        <referenceTo>Nominal_Categories__c</referenceTo>
        <relationshipLabel>Sub Category</relationshipLabel>
        <relationshipName>Sub_Category</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Range_From__c</fullName>
        <label>Range From</label>
        <precision>4</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Range_To__c</fullName>
        <label>Range To</label>
        <precision>4</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Sub Category</label>
    <nameField>
        <label>Sub Category Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sub Category</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

ZumZumFinancials_Dev1/src/objects/Tax_Rate__c.object
<CustomObject>
    <fields>
        <fullName>Tax_Rate__c</fullName>
        <label>Tax Rate</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <label>Tax</label>
    <nameField>
        <label>Tax Rate Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tax</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

ZumZumFinancials_Dev1/src/objects/Time_Sheet__c.object
<CustomObject>
    <fields>
        <fullName>Month__c</fullName>
        <defaultValue>MONTH( TODAY() )</defaultValue>
        <label>Month</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Pending</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Total_Hours__c</fullName>
        <label>Total Hours</label>
        <summarizedField>Time_Sheet_Detail__c.Total_Hours__c</summarizedField>
        <summaryForeignKey>Time_Sheet_Detail__c.Time_Sheet__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Year__c</fullName>
        <defaultValue>YEAR( TODAY() )</defaultValue>
        <label>Year</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Time Sheet</label>
    <nameField>
        <label>Time Sheet Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Time Sheets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

ZumZumFinancials_Dev1/src/objects/Time_Sheet_Detail__c.object
<CustomObject>
    <fields>
        <fullName>Activity_Code__c</fullName>
        <label>Activity Code</label>
        <referenceTo>Activity_Code__c</referenceTo>
        <relationshipName>Time_Sheets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Date__c</fullName>
        <label>Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Narrative__c</fullName>
        <label>Narrative</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Time Sheet Details (Project)</relationshipLabel>
        <relationshipName>Time_Sheets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Approved</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Time_Sheet__c</fullName>
        <label>Time Sheet</label>
        <referenceTo>Time_Sheet__c</referenceTo>
        <relationshipLabel>Time Sheet Details</relationshipLabel>
        <relationshipName>Time_Sheet_Details</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Total_Hours__c</fullName>
        <label>Total Hours</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Time Sheet Detail</label>
    <nameField>
        <label>Time Sheet Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Time Sheet Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

ZumZumFinancials_Dev1/src/classes/SubmitTimeSheetForApproval.cls
public class SubmitTimeSheetForApproval 
{
	/*
	public id timeSheetId  {get; set;}
	public User ur {get; set;}
	public Time_Sheet__c ts {get; set;}
	public String outHouredProjects {get; set;}
	public boolean sureSubmitt {get; set;}
	public boolean sendBack {get; set;}
	public SubmitTimeSheetForApproval ( apexpages.Standardcontroller submitTimeSheet )
	{
		
	}
	public SubmitTimeSheetForApproval ( )
	{
		
	}
	public void init()
	{
		timeSheetId = apexpages.currentPage().getParameters().get('id') ;
		Savepoint sp = Database.setsavepoint();
		try
		{
			if (timeSheetId != null )
			{
				ts = [select Month__c , Owner.Name ,Year__c, Total_Miles__c, Total_Hours__c, Status__c, OwnerId, Name, Id  from Time_Sheet__c where id = : timeSheetId limit 1]  ;
				if (ts.OwnerId != userinfo.getUserId())
				{
					sendBack = true ;
					throw new CustomException('You are Not Authorized to View & Submit this Time Sheet');	
				}
				if(ts.Status__c != 'Approved' && ts.Status__c != 'Submitted_For_Approval' )
				{
					TimeSheet_Model tsObject = new TimeSheet_Model(ts.Id);
					Set<Id> pIds = tsObject.GetProjectsForLevel2Approval();
					system.debug('pids++ '+pIds);
					if(pIds.size() > 0)
					{
						for (Opportunity pr : [select Name from Opportunity where Id IN :pIds] )
						{
							if (outHouredProjects == null )
								outHouredProjects = pr.Name;
							else 			
								outHouredProjects += ' ,' + pr.Name; 	
						}
						apexpages.addMessage( new apexpages.Message( apexpages.Severity.warning , 'Your Contracted Hours for these projects are Exceeded: ' + outHouredProjects  , ' Are you sure to submit this Time Sheet?' ) );
						sureSubmitt = true ; 
					}
					else
					{
						confirmSubmitt() ;
					}
				}
				else if (ts.Status__c == 'Approved')
				{
					sendBack = true ;
					throw new CustomException('Time Sheet is Already Approved' + 'You Can\'t Send it for Approval');	
				}
				else if(ts.Status__c == 'Submitted_For_Approval')
				{
					sendBack = true ;
					throw new CustomException('Time Sheet is Already Submitted for Approval');	
				}
			}
			else
			{
				throw new CustomException('No Time Sheet Exist for this Id');	
			}
		}
		catch (exception e)
		{
			sendBack = true ;
			Database.rollback(sp);
			apexpages.addMessage( new apexpages.Message( Apexpages.Severity.error , e.getMessage() , '' )  );
		}
	}
	public void confirmSubmitt()
	{
		ur = [select Id , Name , Email , UserRoleId from User where id = :Userinfo.getUserId() limit 1 ];
		TimeSheet_Model tsSubmit = new TimeSheet_Model(ts.Id);
		tsSubmit.SubmitForApproval(ur);
		ts.Status__c = 'Submitted_For_Approval';
		update ts;
		sureSubmitt = false ;
		sendBack = true ;
		apexpages.addMessage( new apexpages.Message( Apexpages.Severity.info , 'Time Sheet Submitted for Approval' , '' )  );
	}
	public pagereference back()
	{
		return new pagereference('/' + apexpages.currentPage().getParameters().get('id')) ;
	}
	public static TestMethod void submitForApproval()
	{
		/*
		User ur = [Select Id , Email , Name from User where Id = : '00590000000GMT5'];
		system.runAs(ur)
		{
			Account act = new Account(Name='ABC Company',Type='Customer - Direct');
			insert act;
			Contact cnt = new Contact(LastName = 'test Contact' , AccountId =act.Id ,Email ='test@test.com' );
			insert cnt;
			Tax_Rate__c tx = new Tax_Rate__c(Name = 'VAT' , Tax_Rate__c = 15 );
			insert tx ;
			Nominal_Categories__c  nc = new Nominal_Categories__c (Name = 'this is test');
			insert nc ; 
			Sub_Category__c sb = new Sub_Category__c(Nominal_Categories__c = nc.Id , Range_To__c = 200, Range_From__c=10, Name = 'testSubcatagories');
			insert sb;
			Activity_Code__c ac = new Activity_Code__c(Name = 'Activity 1' , Code__c = 'Activity 1');
			insert ac ;
			Opportunity op = new Opportunity(Name = 'Opportunity abc' , StageName = 'IIT' , Activity_Start__c = date.today(), Activity_End__c = date.today().addDays(5) , CloseDate = date.today().addDays(5));
			insert op;
			Nominal_Account__c nm = new Nominal_Account__c (Sub_Category__c = sb.Id , Tax_Rate__c = tx.Id, S_O__c = true, Name = 'Plumbering', Account_Code__c = 150);
			insert nm ;
			Time_Sheet__c tsinfo = new Time_Sheet__c();
			tsinfo.Month__c = date.today().month();
			tsinfo.Year__c = date.today().year();
			insert tsinfo ;
			Time_Sheet_Detail__c tsd = new Time_Sheet_Detail__c();
			tsd.Activity_Code__c  = ac.Id ;
			tsd.Date__c = date.today();
			tsd.Index__c =  0 ;
			tsd.Narrative__c = 'test Code';
			tsd.Total_Hours__c = 15 ;
			tsd.Total_Miles__c = 20 ;
			tsd.Activity_Code__c = ac.id ;
			tsd.Project__c = op.Id ;
			tsd.Time_Sheet__c = tsinfo.Id;
			insert tsd ;
			Project_Hours__c pH= new Project_Hours__c(Year__c =date.today().year() , User__c = tsinfo.OwnerId , Total_Hours__c = 8 , Project__c = op.Id, Month__c = date.today().month());
			insert pH ;
			system.debug('this is timeSheet ' + tsinfo );
			system.debug('this is Project Pudject: ' + tsd);
			system.debug('this is budget ' + [Select p.Year__c, p.Project__c, p.Name, p.Month__c, p.Id, p.Total_Hours__c From Project_Hours__c p Where p.Project__c=:op.id and User__c=:tsinfo.OwnerId and month__c=:tsinfo.Month__c and year__c=:tsinfo.Year__c limit 1]) ;
			ApexPages.currentPage ().getParameters ().put ('id', tsinfo.id);
			SubmitTimeSheetForApproval obj  = new SubmitTimeSheetForApproval();
			obj.ts = tsinfo ;
	        obj.init();
	       // obj.confirmSubmitt();
	       	obj.back();
	        tsinfo = new Time_Sheet__c();
			tsinfo.Month__c = date.today().month();
			tsinfo.Year__c = date.today().year(); 
			tsinfo.Status__c = 'Approved';
			insert tsinfo ;
			ApexPages.currentPage ().getParameters ().put ('id', tsinfo.id);
			try
			{
				obj.init();
			}
			catch(exception e)
			{
				system.assertEquals('Time Sheet is Already Approved' + 'You Can\'t Send it for Approval', e.getMessage());
			}
			tsinfo = new Time_Sheet__c();
			tsinfo.Month__c = date.today().month();
			tsinfo.Year__c = date.today().year(); 
			tsinfo.Status__c = 'Submitted_For_Approval';
			insert tsinfo ;
			ApexPages.currentPage ().getParameters ().put ('id', tsinfo.id);
			try
			{
				obj.init();
			}
			catch(exception e)
			{
				system.assertEquals('Time Sheet is Already Submitted for Approval', e.getMessage());
			}
			try
	        {	
	        	obj.confirmSubmitt();
	        }
	        catch(exception e)
	        {
	        	system.assertEquals(tsinfo.Status__c+' time Sheet cannot be submitted for approval.', e.getMessage());	
	        }
		}
			
	}
	*/
}