ZumZumFinancials_Dev1/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Nominal_Account__c</fullName>
        <label>Nominal Account</label>
        <referenceTo>Nominal_Account__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

ZumZumFinancials_Dev1/src/objects/CustomerLookup__c.object
<CustomObject>
    <fields>
        <fullName>CustomerAccount__c</fullName>
        <label>CustomerAccount</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>CustomerLookup</relationshipLabel>
        <relationshipName>CustomerLookup</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Nominal_Account__c</fullName>
        <label>Nominal Account</label>
        <referenceTo>Nominal_Account__c</referenceTo>
        <relationshipLabel>CustomerLookup</relationshipLabel>
        <relationshipName>CustomerLookup</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>CustomerLookup</label>
    <nameField>
        <label>CustomerLookup Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CustomerLookup</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

ZumZumFinancials_Dev1/src/objects/Ledger__c.object
<CustomObject>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount Paid</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Details__c</fullName>
        <label>Details</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Net__c</fullName>
        <formula>Credit__c  +  Debit__c  -  Tax__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Net</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Nominal__c</fullName>
        <label>Nominal</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Reference__c</fullName>
        <label>Reference</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Show_On_Transaction__c</fullName>
        <label>Show On Transaction</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Sub_Account_Nominal__c</fullName>
        <label>Sub Account Nominal</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sub_Account__c</fullName>
        <label>Sub Account</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Tax_Code__c</fullName>
        <label>Tax Code</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Tax__c</fullName>
        <label>Tax</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Trans_No__c</fullName>
        <label>Trans. No.</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>BP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>JC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>JD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SR</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Ledger</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Ledger Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ledger</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

ZumZumFinancials_Dev1/src/objects/Nominal_Account__c.object
<CustomObject>
    <fields>
        <fullName>Nominal_Code__c</fullName>
        <formula>TEXT( Account_Code__c )</formula>
        <label>Nominal Code</label>
        <type>Text</type>
    </fields>
    <label>Nominal Account</label>
    <nameField>
        <label>Nominal Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Nominal Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

ZumZumFinancials_Dev1/src/classes/CorrectionsController.cls
public class CorrectionsController { 
	
	public List<Ledger__c> listLedger{get;set;}
	public string numb{get;set;}
	public Ledger__c ledger {get;set;}
	public Ledger__c  objectLedger {get;set;}
	public string retURL{get;set;}
	public Nominal_Account__c objectNominal{get;set;}
	public Nominal_Account__c n{get;set;}
	public CustomerLookup__c LookupAccount{get;set;}
	public string editId{get;set;}	
	public Account o {get;set;} 
	public string AccttNum{get;set;}
	public string NomCode{get;set;}	 
	public CorrectionsController(apexpages.standardcontroller std) 
	{						
		//listLedger = [select Name , Trans_No__c , Type__c , Sub_Account__c ,Nominal__c , Details__c , Reference__c , Net__c , Tax__c , Tax_Code__c , Amount__c from Ledger__c where Show_On_Transaction__c = 1];			
		editId = apexpages.currentPage().getParameters().get('id');
		system.debug('editId : '+editId );
		if(editId != null && editId != '')
		{
			LookupAccount = new CustomerLookup__c();
			objectNominal = new Nominal_Account__c();
			objectLedger = [select Name , Sub_Account_Nominal__c, Trans_No__c , Type__c , Sub_Account__c ,Nominal__c , Details__c , Reference__c , Net__c , Tax__c , Tax_Code__c , Amount__c from Ledger__c where id=: editId];			
			if(objectLedger.Sub_Account__c != objectLedger.Sub_Account_Nominal__c)
			{
				o = [select AccountNumber , id, Name from Account where AccountNumber =: objectLedger.Sub_Account__c ];
				if(o.Id != null)
				{
					LookupAccount.CustomerAccount__c = o.id;
					AccttNum = o.AccountNumber;
				}
			}			
			n = [select Nominal_Code__c , id from Nominal_Account__c where Nominal_Code__c =: objectLedger.Sub_Account_Nominal__c];
			if(n.id != null)
			{	
				LookupAccount.Nominal_Account__c = n.id;
				NomCode = n.Nominal_Code__c ;
			}
		}
		else		
			objectLedger = new Ledger__c();
	}	
	public void SubAccountChanged()
	{		
		o = [select AccountNumber , id, Name from Account where id =: LookupAccount.CustomerAccount__c];
		if(o.Id != null)
		{
			AccttNum = o.AccountNumber;
		}
	}
	public void NominalAccountChanged()
	{
		n = [select Nominal_Code__c , id from Nominal_Account__c where id =: LookupAccount.Nominal_Account__c];
		if(n.id != null)
		{	
			NomCode = n.Nominal_Code__c ;
		}
	}
	public PageReference Mark()
	{ 		
		apexpages.currentPage().getHeaders().put('num',apexpages.currentPage().getParameters().get('num'));
		numb = apexpages.currentpage().getHeaders().get('num'); 
		//system.debug('num : '+ numb);
		retURL = 'https://'+ApexPages.currentPage().getHeaders().get('Host')+'/apex/CorrectionRecord?num='+numb;
		Ledger__c l = [select Type__c from Ledger__c where Name =: numb];
		if(l.Type__c != 'JC' && l.Type__c != 'JD')
			return new PageReference (retURL);
		else
			return null;
	}
	public void init()
	{  
		//editedIndex = integer.valueOf(ApexPages.currentPage().getParameters().get('paramEdit'));
		//decimal num = decimal.valueOf(apexpages.currentPage().getParameters().get('num'));
		numb = apexpages.currentPage().getParameters().get('Host');
		system.debug('init : '+numb );
		ledger = [select Trans_No__c , Type__c , Sub_Account__c ,Nominal__c , Details__c , Reference__c , Net__c , Tax__c , Tax_Code__c , Amount__c from Ledger__c where  Name =: numb];
	}
	
}