ZumZumFinancials_Dev1/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Nominal_Account__c</fullName>
        <label>Nominal Account</label>
        <referenceTo>Nominal_Account__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Tax_Rate__c</fullName>
        <label>Tax Rate</label>
        <referenceTo>Tax_Rate__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

ZumZumFinancials_Dev1/src/objects/Bank_Account__c.object
<CustomObject>
    <fields>
        <fullName>Account_Number__c</fullName>
        <externalId>true</externalId>
        <label>Account Number</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Nominal_Account__c</fullName>
        <label>Nominal Account</label>
        <referenceTo>Nominal_Account__c</referenceTo>
        <relationshipLabel>Bank Accounts</relationshipLabel>
        <relationshipName>Bank_Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Draft</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Deleted</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Bank Account</label>
    <nameField>
        <label>Bank Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bank Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

ZumZumFinancials_Dev1/src/objects/BankTransfer__c.object
<CustomObject>
    <fields>
        <fullName>Date__c</fullName>
        <label>Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Payment_Value__c</fullName>
        <label>Payment Value</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Reference__c</fullName>
        <label>Reference</label>
        <length>225</length>
        <type>Text</type>
    </fields>
    <label>BankTransfer</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>BankTransfer</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

ZumZumFinancials_Dev1/src/objects/Control_Account__c.object
<CustomObject>
    <fields>
        <fullName>Default_Bank__c</fullName>
        <label>Default Bank</label>
        <referenceTo>Nominal_Account__c</referenceTo>
        <relationshipLabel>Control Accounts (Default Bank)</relationshipLabel>
        <relationshipName>Default_Bank</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Nominal_Account__c</fullName>
        <label>Nominal Account</label>
        <referenceTo>Nominal_Account__c</referenceTo>
        <relationshipLabel>Control Accounts</relationshipLabel>
        <relationshipName>Control_Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Control Account</label>
    <nameField>
        <label>Control Accounts</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Control Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

ZumZumFinancials_Dev1/src/objects/Nominal_Account__c.object
<CustomObject>
    <fields>
        <fullName>Account_Code__c</fullName>
        <label>Account Code</label>
        <precision>4</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Expense__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Expense</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Nominal_Code__c</fullName>
        <formula>TEXT( Account_Code__c )</formula>
        <label>Nominal Code</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sub_Category__c</fullName>
        <label>Sub Category</label>
        <referenceTo>Sub_Category__c</referenceTo>
        <relationshipLabel>Nominal Accounts</relationshipLabel>
        <relationshipName>Nominal_Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Tax_Rate__c</fullName>
        <label>Tax Rate</label>
        <referenceTo>Tax_Rate__c</referenceTo>
        <relationshipLabel>Nominal Accounts</relationshipLabel>
        <relationshipName>Nominal_Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Nominal Account</label>
    <nameField>
        <label>Nominal Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Nominal Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

ZumZumFinancials_Dev1/src/objects/Nominal_Categories__c.object
<CustomObject>
    <label>Nominal Category</label>
    <nameField>
        <label>Nominal Categories Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Nominal Categories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

ZumZumFinancials_Dev1/src/objects/Sub_Category__c.object
<CustomObject>
    <fields>
        <fullName>Nominal_Categories__c</fullName>
        <label>Nominal Categories</label>
        <referenceTo>Nominal_Categories__c</referenceTo>
        <relationshipLabel>Sub Category</relationshipLabel>
        <relationshipName>Sub_Category</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Range_From__c</fullName>
        <label>Range From</label>
        <precision>4</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Range_To__c</fullName>
        <label>Range To</label>
        <precision>4</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Sub Category</label>
    <nameField>
        <label>Sub Category Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sub Category</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

ZumZumFinancials_Dev1/src/objects/Tax_Rate__c.object
<CustomObject>
    <fields>
        <fullName>Tax_Rate__c</fullName>
        <label>Tax Rate</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <label>Tax</label>
    <nameField>
        <label>Tax Rate Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tax</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

ZumZumFinancials_Dev1/src/classes/controllerBankTransfer.cls
public class controllerBankTransfer {		
	public list<Bank_Account__c> listBankAccount{get;set;}
	public Control_Account__c defaultBank{get;set;}			
	public BankTransfer__c objectBankTransfer{get;set;}
	public BankTransfer__c curObjectBankTransfer{get;set;}	
	public string retURL;
	public string amount{get;set;}
	public string fromId{get;set;}
	public string toId{get;set;}	
	public Ledger financial;	
		
	public controllerBankTransfer()
	{
		retURL = 'https://'+ApexPages.currentPage().getHeaders().get('Host')+'/apex/BankMenu';		
		objectBankTransfer = new BankTransfer__c();
		objectBankTransfer.Date__c = Date.today();
		amount = '0.00';		
		listBankAccount = [select id,Name, Nominal_Account__r.Nominal_Code__c, Nominal_Account__c from Bank_Account__c where Status__c =: 'Active' order by Nominal_Account__r.Nominal_Code__c];			
	}
	public list<SelectOption> getFromBankAccount()
	{
		List<SelectOption> options = new list<SelectOption>();	
		defaultBank = [Select c.Default_Bank__r.Nominal_Code__c, c.Default_Bank__r.Name, c.Default_Bank__r.Id, c.Default_Bank__c From Control_Account__c c where c.Name= 'Control Accounts'];
		Bank_Account__c opt = [select Name, Nominal_Account__r.Id,Nominal_Account__r.Nominal_Code__c, Nominal_Account__r.Name from Bank_Account__c where Nominal_Account__r.Name =: defaultBank.Default_Bank__r.Name];		
 		options.add(new SelectOption(opt.Nominal_Account__r.Id,opt.Nominal_Account__r.Nominal_Code__c+' - '+opt.Name));		
		for(Bank_Account__c bnk : listBankAccount) 		
		{			
			if(bnk.Nominal_Account__r.id != opt.Nominal_Account__r.Id)
				options.add(new SelectOption(bnk.Nominal_Account__r.Id,bnk.Nominal_Account__r.Nominal_Code__c+' - '+bnk.Name));
		}
		return options;	
	}
	public list<SelectOption> getToBankAccount()
	{
		List<SelectOption> options = new list<SelectOption>();				
 		options.add(new SelectOption('','-- Select --'));		
		for(Bank_Account__c bnk : listBankAccount)
			options.add(new SelectOption(bnk.Nominal_Account__r.Id,bnk.Nominal_Account__r.Nominal_Code__c+' - '+bnk.Name));		
		return options;	
	}
	
	public PageReference Discard()
	{
		return new PageReference(retURL);
	}
	public PageReference Save()
	{
		try
		{					
			ValidationRules();	
			
			objectBankTransfer.Payment_Value__c = decimal.valueOf(amount);
			BankTransfer__c bnkTransfer = new BankTransfer__c(Reference__c = objectBankTransfer.Reference__c, Description__c = objectBankTransfer.Description__c, Date__c = objectBankTransfer.Date__c, Payment_Value__c = objectBankTransfer.Payment_Value__c);
			insert bnkTransfer;
												
			CustomerRefund_BudgetModel bModel = new CustomerRefund_BudgetModel();
			bModel.AddDebit(toId, objectBankTransfer.Payment_Value__c , string.valueOf(objectBankTransfer.Date__c));
			bModel.AddCredit(fromId, objectBankTransfer.Payment_Value__c , string.valueOf(objectBankTransfer.Date__c));
 			bModel.newSave();  			
 			
 			financial =  new Ledger(); 			
 			financial.AddBankTransferTransaction( objectBankTransfer.Payment_Value__c , toId, fromId, objectBankTransfer.Description__c , objectBankTransfer.Reference__c, objectBankTransfer.Date__c ); 											
			financial.Save(); 
					
			return new PageReference(retURL);		
		}	
		catch(exception e)
		{
			ApexPages.AddMessages(e);
			return null;
		}
	}
	public void ValidationRules()	
	{
		if(fromId == null || toId == null)
			throw new CustomException('Select Bank Account first');
		if(fromId == toId)
			throw new CustomException('You must select different Bank Accounts');
		if(objectBankTransfer.Date__c == null)			
			throw new CustomException('You must enter date to save the record');
		if(Amount == null || Amount == '')
			Amount = '0.0'; 		
		if(!Pattern.matches('^[0-9]+(.[0-9]{1,2})?$', Amount))
			throw new CustomException('Enter an Amount first');
		if(decimal.valueOf(Amount) <= 0)
				throw new CustomException('Enter an Amount first');
	}	
	private static testMethod void controllerBankTransfer_Test()
	{
		Tax_Rate__c tx = new Tax_Rate__c(Name = 'VAT' , Tax_Rate__c = 15 );
		insert tx ;
    	Nominal_Categories__c  nc = new Nominal_Categories__c (Name = 'this is test');
		insert nc ; 
		Sub_Category__c sb = new Sub_Category__c(Nominal_Categories__c = nc.Id , Range_To__c = 200, Range_From__c=10, Name = 'testSubcatagories');
		insert sb;
		Nominal_Account__c nm = new Nominal_Account__c (Sub_Category__c = sb.Id , Tax_Rate__c = tx.Id, Expense__c = true, Name = 'Plumbering', Account_Code__c = 1222);
		insert nm ;
		Nominal_Account__c nm1 = new Nominal_Account__c (Sub_Category__c = sb.Id , Tax_Rate__c = tx.Id, Expense__c = true, Name = 'Plumbering', Account_Code__c = 1299);
		insert nm1 ;		
		Bank_Account__c ba = new Bank_Account__c (Nominal_Account__c = nm.id, Status__c = 'Active' , Name = 'Bank From Account' , Account_Number__c = 'B745');
		insert ba;
		Bank_Account__c ba1 = new Bank_Account__c (Nominal_Account__c = nm1.id, Status__c = 'Active' , Name = 'Bank To Account' , Account_Number__c = 'B4165');
		insert ba1;
		
		controllerBankTransfer bnkTransfr = new controllerBankTransfer();
		List<SelectOption> FrmbnkAcctt = bnkTransfr.getFromBankAccount();								
		List<SelectOption> TobnkAcctt = bnkTransfr.getToBankAccount();
		try
		{
			bnkTransfr.ValidationRules();
		}
		catch(exception e)
		{
			system.assertEquals(e.getMessage(), 'Select Bank Account first');
		}
		bnkTransfr.fromId = nm.Id;
		try
		{
			bnkTransfr.ValidationRules();
		}
		catch(exception e)
		{
			system.assertEquals(e.getMessage(), 'Select Bank Account first');
		}
		bnkTransfr.toId = nm.Id;
		try
		{
			bnkTransfr.ValidationRules();
		}
		catch(exception e)
		{
			system.assertEquals(e.getMessage(), 'You must select different Bank Accounts');
		}
		bnkTransfr.toId = nm1.Id;
		bnkTransfr.objectBankTransfer.Date__c = null;
		try
		{
			bnkTransfr.ValidationRules();
		}
		catch(exception e)
		{
			system.assertEquals(e.getMessage(), 'You must enter date to save the record');
		}
		bnkTransfr.objectBankTransfer.Date__c = Date.today();
		bnkTransfr.amount = null;
		try
		{
			bnkTransfr.ValidationRules();
		}
		catch(exception e)
		{
			system.assertEquals(e.getMessage(), 'Enter an Amount first');
		}
		bnkTransfr.amount = 'asdg';
		try
		{
			bnkTransfr.ValidationRules();
		}
		catch(exception e)
		{
			system.assertEquals(e.getMessage(), 'Enter an Amount first');
		}
		bnkTransfr.amount = '4';
		bnkTransfr.Save();
		bnkTransfr.Discard();
		
	}  
}