ZumZumFinancials_Dev1/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Nominal_Account__c</fullName>
        <label>Nominal Account</label>
        <referenceTo>Nominal_Account__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

ZumZumFinancials_Dev1/src/objects/Nominal_Account__c.object
<CustomObject>
    <label>Nominal Account</label>
    <nameField>
        <label>Nominal Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Nominal Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

ZumZumFinancials_Dev1/src/objects/RecurringTransaction__c.object
<CustomObject>
    <description>Made by BOSS</description>
    <fields>
        <fullName>Finish_Date__c</fullName>
        <label>Finish Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Name_of__c</fullName>
        <label>Frequency Period</label>
        <picklist>
            <picklistValues>
                <fullName>Day(s)</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Week(s)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Month(s)</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Net_Amount__c</fullName>
        <label>Net Amount</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>No_of__c</fullName>
        <label>Frequency</label>
        <precision>2</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Nominal_Account__c</fullName>
        <label>Nominal Account</label>
        <referenceTo>Nominal_Account__c</referenceTo>
        <relationshipLabel>RecurringTransaction</relationshipLabel>
        <relationshipName>RecurringTransaction</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>TransactionType__c</fullName>
        <label>Transaction Type</label>
        <picklist>
            <picklistValues>
                <fullName>Bank/Cash/Credit Card Payment</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Bank/Cash/Credit Card Receipt</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bank/Cash/Credit Card Transfer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Customer payment on Account</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>RecurringTransaction</label>
    <nameField>
        <label>Recurring Transaction Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RecurringTransaction</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

ZumZumFinancials_Dev1/src/classes/BankRecurringModel.cls
public class BankRecurringModel {
	public RecurringTransaction__c objRecurringTransaction {get;set;}
	public decimal a {get;set;}	
	public BankRecurringModel(RecurringTransaction__c  rt)
	{
		objRecurringTransaction  = rt;		
	}
	public void Save()
	{
		savePoint sp = Database.setSavepoint();
		try
		{
			ValidationRules();
			//if(editId != null)
				upsert objRecurringTransaction ;
			//else
//				insert objRecurringTransaction ;
		}
		catch(exception e)
		{
			Database.rollback(sp); 
			throw new CustomException('Unable to Save \n'+e.getMessage());			
		}
	}
	public void ValidationRules()
	{
		if(objRecurringTransaction.TransactionType__c == null)		
			throw new CustomException('Select Transaction type first');
		if(objRecurringTransaction.Nominal_Account__c == null)		
			throw new CustomException('Select Nominal Account first');
		if(objRecurringTransaction.Net_Amount__c == 0.00)		
			throw new CustomException('Enter Amount first');
		if(objRecurringTransaction.Name_of__c == null)		
			throw new CustomException('Select Time Period first');
		if(objRecurringTransaction.No_of__c == 0)		
			throw new CustomException('Enter Time Period first');
		if(objRecurringTransaction.Start_Date__c == null)		
			throw new CustomException('Enter Start Date first');
		if(objRecurringTransaction.Finish_Date__c == null)		
			throw new CustomException('Enter Finish Date first');
		/*if(REGEX( objRecurringTransaction.No_of__c,"[0-9]+""))
			throw new CustomException('Enter Frequency as a number');*/		
				 
			
	}
}