ZumZumFinancials_Dev1/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Nominal_Account__c</fullName>
        <label>Nominal Account</label>
        <referenceTo>Nominal_Account__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Tax_Rate__c</fullName>
        <label>Tax Rate</label>
        <referenceTo>Tax_Rate__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

ZumZumFinancials_Dev1/src/objects/Bank_Account__c.object
<CustomObject>
    <fields>
        <fullName>Nominal_Account__c</fullName>
        <label>Nominal Account</label>
        <referenceTo>Nominal_Account__c</referenceTo>
        <relationshipLabel>Bank Accounts</relationshipLabel>
        <relationshipName>Bank_Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Bank Account</label>
    <nameField>
        <label>Bank Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bank Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

ZumZumFinancials_Dev1/src/objects/Nominal_Account__c.object
<CustomObject>
    <fields>
        <fullName>Nominal_Code__c</fullName>
        <formula>TEXT( Account_Code__c )</formula>
        <label>Nominal Code</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Tax_Rate__c</fullName>
        <label>Tax Rate</label>
        <referenceTo>Tax_Rate__c</referenceTo>
        <relationshipLabel>Nominal Accounts</relationshipLabel>
        <relationshipName>Nominal_Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Nominal Account</label>
    <nameField>
        <label>Nominal Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Nominal Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

ZumZumFinancials_Dev1/src/objects/RecurringTransaction__c.object
<CustomObject>
    <description>Made by BOSS</description>
    <fields>
        <fullName>Bank_Account__c</fullName>
        <label>Bank Account</label>
        <referenceTo>Bank_Account__c</referenceTo>
        <relationshipLabel>RecurringTransaction</relationshipLabel>
        <relationshipName>RecurringTransaction</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Details__c</fullName>
        <label>Details</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Finish_Date__c</fullName>
        <label>Finish Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Last_Posted__c</fullName>
        <label>Last Posted</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Name_of__c</fullName>
        <label>Frequency Period</label>
        <picklist>
            <picklistValues>
                <fullName>Day(s)</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Week(s)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Month(s)</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Net_Amount__c</fullName>
        <label>Net Amount</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Next_Transaction_Date__c</fullName>
        <label>Next Transaction Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>No_of__c</fullName>
        <label>Frequency</label>
        <precision>2</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Nominal_Account__c</fullName>
        <label>Nominal Account</label>
        <referenceTo>Nominal_Account__c</referenceTo>
        <relationshipLabel>RecurringTransaction</relationshipLabel>
        <relationshipName>RecurringTransaction</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Reference__c</fullName>
        <label>Reference</label>
        <length>225</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Required_Posting__c</fullName>
        <label>Required Posting</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Suspend_Posting__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Suspend Posting</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Tax_Rate__c</fullName>
        <label>Tax Rate</label>
        <referenceTo>Tax_Rate__c</referenceTo>
        <relationshipLabel>RecurringTransaction</relationshipLabel>
        <relationshipName>RecurringTransaction</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>TransactionType__c</fullName>
        <label>Transaction Type</label>
        <picklist>
            <picklistValues>
                <fullName>Bank/Cash/Credit Card Payment</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Bank/Cash/Credit Card Receipt</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bank/Cash/Credit Card Transfer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Customer payment on Account</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>VAT__c</fullName>
        <label>VAT Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>RecurringTransaction</label>
    <nameField>
        <label>Recurring Transaction Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RecurringTransaction</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

ZumZumFinancials_Dev1/src/objects/Tax_Rate__c.object
<CustomObject>
    <fields>
        <fullName>Tax_Rate__c</fullName>
        <label>Tax Rate</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <label>Tax</label>
    <nameField>
        <label>Tax Rate Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tax</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

ZumZumFinancials_Dev1/src/classes/RecurringTransactionBatchProcess.cls
global class RecurringTransactionBatchProcess implements Database.Batchable<sObject>
{
	global RecurringTransactionBatchProcess()
	{
	
	}
	
	global Database.QueryLocator Start(Database.BatchableContext bc)
	{
		return Database.GetQueryLocator([Select r.VAT__c, r.TransactionType__c, r.Tax_Rate__c, r.Tax_Rate__r.Name, r.Suspend_Posting__c, r.Start_Date__c, 
									r.Required_Posting__c, r.Reference__c, r.Nominal_Account__r.Nominal_Code__c, r.No_of__c, r.Net_Amount__c, 
									r.Name_of__c, r.Name, r.Last_Posted__c, r.Id, r.Finish_Date__c, r.Details__c, r.Bank_Account__c, r.Bank_Account__r.Nominal_Account__r.Nominal_Code__c 
									From RecurringTransaction__c r
									Where Next_Transaction_Date__c=:date.today()
									and r.Finish_Date__c<=:date.today()]);
	}
	
	global void Execute(Database.BatchableContext bc, List<sObject> scope)
	{
		Savepoint sp = database.SetSavePoint();
		try
		{
			Ledger lTransaction = new Ledger();
			List<RecurringTransaction__c> transactionRecords = (List<RecurringTransaction__c>) scope;
			for(RecurringTransaction__c trans : transactionRecords)
			{
				if(trans.TransactionType__c=='Bank/Cash/Credit Card Payment')
				{
					lTransaction.AddBankPaymentTransaction(trans.Net_Amount__c,trans.Bank_Account__r.Nominal_Account__r.Nominal_Code__c,trans.Nominal_Account__r.Nominal_Code__c,trans.Details__c,trans.Reference__c,trans.Tax_Rate__r.Name,trans.VAT__c);					
				}
				else if(trans.TransactionType__c=='Bank/Cash/Credit Card Receipt')
				{
					lTransaction.AddBankReceiptTransaction(trans.Net_Amount__c,trans.Bank_Account__r.Nominal_Account__r.Nominal_Code__c,trans.Nominal_Account__r.Nominal_Code__c,trans.Details__c,trans.Reference__c,trans.Tax_Rate__c,trans.VAT__c);
				}
				else if(trans.TransactionType__c=='Bank/Cash/Credit Card Transfer')
				{
					lTransaction.AddBankTransferTransaction(trans.Net_Amount__c, trans.Bank_Account__r.Nominal_Account__r.Nominal_Code__c, trans.Nominal_Account__r.Nominal_Code__c, trans.Details__c , trans.Reference__c, date.today());
				}
				else if(trans.TransactionType__c=='Customer payment on Account')
				{
					lTransaction.AddSalesPaymentOnAccountTransaction(trans.Bank_Account__r.Nominal_Account__r.Nominal_Code__c, 'put customer account number here', trans.Nominal_Account__r.Nominal_Code__c, trans.Net_Amount__c, trans.Reference__c);
				}
				controllerRecurringTransaction.SetNextRunDate(trans);
			}
			lTransaction.Save();
			update transactionRecords;
		}
		catch(Exception ex)
		{
			database.rollback(sp);		
		}
	}
	
	global void Finish(Database.BatchableContext bc)
	{
		
	}
}