ZumZumFinancials_Dev1/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Entity_Email__c</fullName>
        <description>Entity&apos;s main email address</description>
        <inlineHelpText>Enter entity&apos;s main email address</inlineHelpText>
        <label>Entity Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Nominal_Account__c</fullName>
        <label>Nominal Account</label>
        <referenceTo>Nominal_Account__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Tax_Rate__c</fullName>
        <label>Tax Rate</label>
        <referenceTo>Tax_Rate__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

ZumZumFinancials_Dev1/src/objects/Nominal_Account__c.object
<CustomObject>
    <fields>
        <fullName>Account_Code__c</fullName>
        <label>Account Code</label>
        <precision>4</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>S_O__c</fullName>
        <defaultValue>true</defaultValue>
        <label>S O</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Sub_Category__c</fullName>
        <label>Sub Category</label>
        <referenceTo>Sub_Category__c</referenceTo>
        <relationshipLabel>Nominal Accounts</relationshipLabel>
        <relationshipName>Nominal_Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Tax_Rate__c</fullName>
        <label>Tax Rate</label>
        <referenceTo>Tax_Rate__c</referenceTo>
        <relationshipLabel>Nominal Accounts</relationshipLabel>
        <relationshipName>Nominal_Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Nominal Account</label>
    <nameField>
        <label>Nominal Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Nominal Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

ZumZumFinancials_Dev1/src/objects/Nominal_Categories__c.object
<CustomObject>
    <label>Nominal Category</label>
    <nameField>
        <label>Nominal Categories Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Nominal Categories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

ZumZumFinancials_Dev1/src/objects/Sales_Order__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <label>Customer Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Sales Orders</relationshipLabel>
        <relationshipName>Sales_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Order_By__c</fullName>
        <label>Order By</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Sales_Orders2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Order_Date__c</fullName>
        <label>Order Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Quote_Number__c</fullName>
        <label>Quote Number</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending</fullName>
                <default>true</default>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Total_Gross__c</fullName>
        <label>Total Gross</label>
        <summarizedField>Sales_Order_Line_Items__c.Total_Amount__c</summarizedField>
        <summaryForeignKey>Sales_Order_Line_Items__c.Sales_Order__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <label>Sales Order</label>
    <nameField>
        <label>Order No.</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

ZumZumFinancials_Dev1/src/objects/Sales_Order_Line_Items__c.object
<CustomObject>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Narrative__c</fullName>
        <label>Narrative</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Nominal_Account__c</fullName>
        <label>Nominal Account</label>
        <referenceTo>Nominal_Account__c</referenceTo>
        <relationshipLabel>Sales Order Line Items</relationshipLabel>
        <relationshipName>Sales_Order_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <label>Quantity</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Sales_Order__c</fullName>
        <label>Sales Order</label>
        <referenceTo>Sales_Order__c</referenceTo>
        <relationshipLabel>Sales Order Line Items</relationshipLabel>
        <relationshipName>Sales_Order_Line_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Serial_No__c</fullName>
        <label>Serial No</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Tax_Rate__c</fullName>
        <label>Tax Rate</label>
        <referenceTo>Tax_Rate__c</referenceTo>
        <relationshipLabel>Sales Order Line Items</relationshipLabel>
        <relationshipName>Sales_Order_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>VAT_Amount__c</fullName>
        <label>VAT Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Sales Order Line Items</label>
    <nameField>
        <label>Sales Order Line Items Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Order Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

ZumZumFinancials_Dev1/src/objects/Sub_Category__c.object
<CustomObject>
    <fields>
        <fullName>Nominal_Categories__c</fullName>
        <label>Nominal Categories</label>
        <referenceTo>Nominal_Categories__c</referenceTo>
        <relationshipLabel>Sub Category</relationshipLabel>
        <relationshipName>Sub_Category</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Range_From__c</fullName>
        <label>Range From</label>
        <precision>4</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Range_To__c</fullName>
        <label>Range To</label>
        <precision>4</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Sub Category</label>
    <nameField>
        <label>Sub Category Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sub Category</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

ZumZumFinancials_Dev1/src/objects/Tax_Rate__c.object
<CustomObject>
    <fields>
        <fullName>Tax_Rate__c</fullName>
        <label>Tax Rate</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <label>Tax</label>
    <nameField>
        <label>Tax Rate Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tax</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

ZumZumFinancials_Dev1/src/classes/SendSalesOrderAsEmail.cls
public class SendSalesOrderAsEmail 
{
	/*
	public list<emailStruct> emaillist {get; set;}
	public string customEmails {get; set;}
	public Sales_Order__c sO {get; set;}
	public boolean sendBack {get; set;}
	public boolean showPage {get; set;}
	public boolean sendEmailtoViewer {set; get;}
	public SendSalesOrderAsEmail ( apexpages.Standardcontroller sendPurchaseOrderAsEmail )
	{
	
	}
	public SendSalesOrderAsEmail ( )
	{
	
	}
	public pagereference init()
	{
		try
		{
			Id orderId = apexpages.currentPage().getParameters().get('id');
			sO = [Select Id , Status__c, Name , Account__r.Entity_Email__c from  Sales_Order__c where Id = :orderId ];
			if (sO.Status__c != 'Approved')
			{
				showPage = false ;
				sendBack = true ;
				throw new CustomException(sO.Name +' is not Approved, It cannot be Send as Email');
			}
			showPage = true;
			emaillist = new list<emailStruct> ();
			for ( Contact con : [Select c.Email, c.FirstName, c.LastName,  c.Department, c.AccountId From Contact c where c.AccountId = :sO.Account__c AND c.Email != null order By Name ASC limit 1000] )
			{
				emaillist.add( new emailStruct(con.Email ,  con.FirstName+' '+con.LastName , false  ) );	
			}
			system.debug('this is email list' + emaillist);
			return null;
		}
		catch(exception e)
		{
			//apexpages.addMessages(e);
			apexpages.addMessage( new apexpages.Message( apexpages.Severity.info , e.getMessage() , '' ));
			return null ;
		}
	}
	public pagereference back()
	{
		return new pagereference('/' + apexpages.currentPage().getParameters().get('id') );
	}
	public pagereference sendEmails()
	{
		try
		{
			String[] emails = new String[]{};
			for (emailStruct em : emaillist )
			{
				if ( em.isSelected == true )	
					emails.add(em.Email)	;
			}
			string[] invalidAddresses = new string[]{};
			for(string em : customEmails.split(',' , 0))
			{
				if(OrderValidation.emailvalidate(em) ==true )
				{
					emails.add(em);
				}
				else
				{
					invalidAddresses.add(em);
					break;
				}
			}
			if (emails.size() == 0)
			{
				apexpages.addMessage( new apexpages.Message ( apexpages.Severity.error , 'No email Selected' , 'Please Enter Email Address' ) );
				return null; 	
			}
			if (invalidAddresses.size() > 0 )
			{
				apexpages.addMessage( new apexpages.Message ( apexpages.Severity.error , invalidAddresses[0] , ' is an Invalid Email Address' ) );
				return null; 
			}
			List<SalesOrderApprovals__c> approveStatus = [select Status__c from SalesOrderApprovals__c where Sales_Order__c = :sO.Id limit 1];
			string emailAddress = '' ;
			PageReference pdf = page.Sales_Order_Pdf_Veiw;     
            //pdf.getParameters().put('generatePdf','1');  
            pdf.getParameters().put('id',sO.Id);    
            pdf.setRedirect(true);     
            // Grab it!      
            Blob b = pdf.getContent();
            // Create an email attachment
            string userEmail = [select Email from user where Id = : userinfo.getUserId()].Email; 
            Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
            if (sendEmailtoViewer == true && ( userEmail !=null || userEmail !='' ))
				mail.setBccAddresses(new String[] {userEmail });
			mail.setToAddresses(emails);
			mail.setSenderDisplayName('Zumzum RDI Application');
			mail.setSubject('Please Check Sales Order :' + sO.Name );
			mail.setHtmlBody('Please Check Sales Order information for your Sales order:'+ sO.Name  + ' <br/><a href=https://c.cs0.visual.force.com/apex/Recievegoods?id='+sO.Id+'>click here</a>'  );
			Messaging.EmailFileAttachment efa = new Messaging.EmailFileAttachment();     
            efa.setFileName('Sales Order Info.pdf'); // neat - set name of PDF     
            efa.setBody(b);	
			mail.setFileAttachments(new Messaging.EmailFileAttachment[]{efa});
			Messaging.sendEmail(new Messaging.SingleEmailMessage[] { mail });
			sendBack  = true ;
			apexpages.addMessage( new apexpages.Message( apexpages.Severity.info , 'Email is sent to Sales Order Account' , '' ));
			return null;
		}	
		catch(exception e)
		{
			apexpages.addMessage( new apexpages.Message( apexpages.Severity.info , e.getMessage() , '' ));	
			return null; 	
		}	
	}
	public class emailStruct
	{
		public string Email {get; set;}
		public Boolean isSelected {get; set;}
		public string contactName {get; set;}
		public emailStruct(string contactEmail , string name , boolean emailSelected)
		{
			Email = contactEmail ;
			isSelected = emailSelected ;
			contactName = name ;	
		} 
	}
	private static TestMethod void emailSalesOrder()
	{
		Account act = new Account(Name='ABC Company',Type='Customer - Direct');
		insert act;
		Contact cnt = new Contact(LastName = 'test Contact' , AccountId =act.Id ,Email ='test@test.com' );
		insert cnt;
		Tax_Rate__c tx = new Tax_Rate__c(Name = 'VAT' , Tax_Rate__c = 15 );
		insert tx ;
		Nominal_Categories__c  nc = new Nominal_Categories__c (Name = 'this is test');
		insert nc ; 
		Sub_Category__c sb = new Sub_Category__c(Nominal_Categories__c = nc.Id , Range_To__c = 200, Range_From__c=10, Name = 'testSubcatagories');
		insert sb;
		Nominal_Account__c nm = new Nominal_Account__c (Sub_Category__c = sb.Id , Tax_Rate__c = tx.Id, S_O__c = true, Name = 'Plumbering', Account_Code__c = 150);
		insert nm ;
		Sales_Order__c Cont = new Sales_Order__c(Quote_Number__c = '0001' , Name = '00050' , Account__c = act.Id  , Order_Date__c = date.today() , Total_Gross__c = 150 , Status__c = 'Approved' , Order_By__c = userinfo.getUserId());
		insert Cont ;
		
		Sales_Order_Line_Items__c tmpline = new Sales_Order_Line_Items__c();
		tmpline.Serial_No__c = 1 ;
		tmpline.Amount__c = 20 ;
		tmpline.Total_Gross__c = 20 ;
		tmpline.Quantity__c = 1 ;
		tmpline.Narrative__c = 'item name' ;
		tmpline.VAT_Amount__c = 0 ;
		tmpline.Nominal_Account__c = nm.Id;
		tmpline.Tax_Rate__c = tx.id ;
		tmpline.Sales_Order__c = Cont.Id ;
		insert tmpline ;
		ApexPages.currentPage ().getParameters ().put ('id', Cont.id);
		//ApexPages.currentPage ().getParameters ().put ('delID', Cont.id);    
        ApexPages.StandardController stdCon = new ApexPages.StandardController (Cont);
        SendSalesOrderAsEmail obj  = new SendSalesOrderAsEmail();
        obj.init();
		obj.emaillist[0].isSelected = true;
		obj.customEmails = 'test@test.com,test2@test.com';
		obj.sendEmails();
		obj.back();
	}
	private static TestMethod void emailSalesOrderinvalidemail()
	{
		Account act = new Account(Name='ABC Company',Type='Customer - Direct');
		insert act;
		Contact cnt = new Contact(LastName = 'test Contact' , AccountId =act.Id ,Email ='test@test.com' );
		insert cnt;
		Tax_Rate__c tx = new Tax_Rate__c(Name = 'VAT' , Tax_Rate__c = 15 );
		insert tx ;
		Nominal_Categories__c  nc = new Nominal_Categories__c (Name = 'this is test');
		insert nc ; 
		Sub_Category__c sb = new Sub_Category__c(Nominal_Categories__c = nc.Id , Range_To__c = 200, Range_From__c=10, Name = 'testSubcatagories');
		insert sb;
		Nominal_Account__c nm = new Nominal_Account__c (Sub_Category__c = sb.Id , Tax_Rate__c = tx.Id, S_O__c = true, Name = 'Plumbering', Account_Code__c = 150);
		insert nm ;
		Sales_Order__c Cont = new Sales_Order__c(Quote_Number__c = '0001' , Name = '00050' , Account__c = act.Id  , Order_Date__c = date.today() , Total_Gross__c = 150 , Status__c = 'Pending' , Order_By__c = userinfo.getUserId());
		insert Cont ;
		
		Sales_Order_Line_Items__c tmpline = new Sales_Order_Line_Items__c();
		tmpline.Serial_No__c = 1 ;
		tmpline.Amount__c = 20 ;
		tmpline.Total_Gross__c = 20 ;
		tmpline.Quantity__c = 1 ;
		tmpline.Narrative__c = 'item name' ;
		tmpline.VAT_Amount__c = 0 ;
		tmpline.Nominal_Account__c = nm.Id;
		tmpline.Tax_Rate__c = tx.id ;
		tmpline.Sales_Order__c = Cont.Id ;
		insert tmpline ;
		ApexPages.currentPage ().getParameters ().put ('id', Cont.id);
		//ApexPages.currentPage ().getParameters ().put ('delID', Cont.id);    
        ApexPages.StandardController stdCon = new ApexPages.StandardController (Cont);
        SendSalesOrderAsEmail obj  = new SendSalesOrderAsEmail();
        try
        {
        	obj.init();
        }
        catch(exception e)
        {
        	system.assertEquals(Cont.Name +' is not Approved, It cannot be Send as Email', e.getMessage());
        }
		obj.customEmails = 'test@test.com,test2@test.com,785783647r';
		obj.sendEmails();
		obj.back();
	}
	
	private static TestMethod void emailSalesOrdernull()
	{
		//ApexPages.currentPage ().getParameters ().put ('id', Cont.id);
		//ApexPages.currentPage ().getParameters ().put ('delID', Cont.id);    
        //ApexPages.StandardController stdCon = new ApexPages.StandardController (Cont);
        SendSalesOrderAsEmail obj  = new SendSalesOrderAsEmail();
        obj.init();
		obj.sendEmails();
		obj.back();
	}
	*/
}