ZumZumFinancials_Dev1/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Nominal_Account__c</fullName>
        <label>Nominal Account</label>
        <referenceTo>Nominal_Account__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Tax_Rate__c</fullName>
        <label>Tax Rate</label>
        <referenceTo>Tax_Rate__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

ZumZumFinancials_Dev1/src/objects/Expense_Sheet__c.object
<CustomObject>
    <fields>
        <fullName>Claim_No__c</fullName>
        <label>Claim No</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Month_Number__c</fullName>
        <label>Month Number</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Month__c</fullName>
        <label>Month</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Pending</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Total_Gross__c</fullName>
        <label>Total Gross</label>
        <summarizedField>Expense_Sheet_Detail__c.Total_Gross__c</summarizedField>
        <summaryForeignKey>Expense_Sheet_Detail__c.Expense_Sheet__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Total_Net__c</fullName>
        <label>Total Net</label>
        <summarizedField>Expense_Sheet_Detail__c.Total_Net__c</summarizedField>
        <summaryForeignKey>Expense_Sheet_Detail__c.Expense_Sheet__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Total_VAT__c</fullName>
        <label>Total VAT</label>
        <summarizedField>Expense_Sheet_Detail__c.Total_VAT__c</summarizedField>
        <summaryForeignKey>Expense_Sheet_Detail__c.Expense_Sheet__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Year__c</fullName>
        <label>Year</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Expense Sheet</label>
    <nameField>
        <label>Expense Sheet Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Expense Sheet</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

ZumZumFinancials_Dev1/src/objects/Expense_Sheet_Detail__c.object
<CustomObject>
    <fields>
        <fullName>Date__c</fullName>
        <label>Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Expense_Sheet__c</fullName>
        <label>Expense Sheet</label>
        <referenceTo>Expense_Sheet__c</referenceTo>
        <relationshipLabel>Expense Sheet Detail</relationshipLabel>
        <relationshipName>Expense_Sheet_Detail</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Narrative__c</fullName>
        <label>Narrative</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Nominal_Account__c</fullName>
        <label>Nominal Account</label>
        <referenceTo>Nominal_Account__c</referenceTo>
        <relationshipLabel>Expense Sheet Detail</relationshipLabel>
        <relationshipName>Expense_Sheet_Detail</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Expense Sheet Detail</relationshipLabel>
        <relationshipName>Expense_Sheet_Detail</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <label>Quantity</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending</fullName>
                <default>true</default>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Tax_Rate__c</fullName>
        <label>Tax Rate</label>
        <referenceTo>Tax_Rate__c</referenceTo>
        <relationshipLabel>Expense Sheet Detail</relationshipLabel>
        <relationshipName>Expense_Sheet_Detail</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Total_Gross__c</fullName>
        <label>Total Gross</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Total_Net__c</fullName>
        <label>Total Net</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Total_VAT__c</fullName>
        <label>Total VAT</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Expense Sheet Detail</label>
    <nameField>
        <label>Expense Sheet Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Expense Sheet Detail</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

ZumZumFinancials_Dev1/src/objects/Nominal_Account__c.object
<CustomObject>
    <fields>
        <fullName>Account_Code__c</fullName>
        <label>Account Code</label>
        <precision>4</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Expense__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Expense</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Sub_Category__c</fullName>
        <label>Sub Category</label>
        <referenceTo>Sub_Category__c</referenceTo>
        <relationshipLabel>Nominal Accounts</relationshipLabel>
        <relationshipName>Nominal_Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Tax_Rate__c</fullName>
        <label>Tax Rate</label>
        <referenceTo>Tax_Rate__c</referenceTo>
        <relationshipLabel>Nominal Accounts</relationshipLabel>
        <relationshipName>Nominal_Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Nominal Account</label>
    <nameField>
        <label>Nominal Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Nominal Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

ZumZumFinancials_Dev1/src/objects/Nominal_Categories__c.object
<CustomObject>
    <label>Nominal Category</label>
    <nameField>
        <label>Nominal Categories Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Nominal Categories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

ZumZumFinancials_Dev1/src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Activity_End__c</fullName>
        <defaultValue>today()+365</defaultValue>
        <description>Expected activity end date, may post date eligibility end date</description>
        <inlineHelpText>Enter the expected activity end date, may post date eligibility end date</inlineHelpText>
        <label>Activity End</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Activity_Start__c</fullName>
        <defaultValue>today()</defaultValue>
        <description>Expected activity start date, may pre-date eligibility start date</description>
        <inlineHelpText>Enter the expected activity start date, may pre-date eligibility start date</inlineHelpText>
        <label>Activity Start</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Sub_Project__c</fullName>
        <label>Project</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Sub Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

ZumZumFinancials_Dev1/src/objects/Sub_Category__c.object
<CustomObject>
    <fields>
        <fullName>Nominal_Categories__c</fullName>
        <label>Nominal Categories</label>
        <referenceTo>Nominal_Categories__c</referenceTo>
        <relationshipLabel>Sub Category</relationshipLabel>
        <relationshipName>Sub_Category</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Range_From__c</fullName>
        <label>Range From</label>
        <precision>4</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Range_To__c</fullName>
        <label>Range To</label>
        <precision>4</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Sub Category</label>
    <nameField>
        <label>Sub Category Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sub Category</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

ZumZumFinancials_Dev1/src/objects/Tax_Rate__c.object
<CustomObject>
    <fields>
        <fullName>Tax_Rate__c</fullName>
        <label>Tax Rate</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <label>Tax</label>
    <nameField>
        <label>Tax Rate Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tax</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

ZumZumFinancials_Dev1/src/classes/SubmitExpenseSheetForApproval.cls
public class SubmitExpenseSheetForApproval 
{
	/*
	public Id expenseSheetId {get; set;}
	public User ur {get; set;}
	public boolean sendBack {get; set;}
	public SubmitExpenseSheetForApproval( apexpages.Standardcontroller submitExpenseSheet )
	{
		
	}
	public SubmitExpenseSheetForApproval()
	{
		
	}
	public void submitExpenseSheet()
	{
		Savepoint sp = Database.setsavepoint(); 
		try
		{
			expenseSheetId = apexpages.currentPage().getParameters().get('id');
			Expense_Sheet__c expSheetinfo = [Select e.Total_VAT__c, e.Total_Net__c, e.Total_Gross__c, e.Status__c, e.OwnerId, e.Name, e.Month__c, e.Id, e.Claim_No__c From Expense_Sheet__c e where e.Id = :expenseSheetId ];
			if (expSheetinfo != null)
			{
				ur = [select Id , Name , Email , UserRoleId from User where id = :Userinfo.getUserId() limit 1 ];
					ExpenseSheet_Model exp = new ExpenseSheet_Model(expSheetinfo.Id) ;
					exp.SubmitForApproval(ur);
					expSheetinfo.Status__c = 'Submitted_For_Approval';
					update(expSheetinfo);
					apexpages.addMessage( new apexpages.Message( apexpages.Severity.CONFIRM , 'Expense Sheet '+ expSheetinfo.Name + ' is submitted for approval' ,''  ) );
					sendBack = true ;
					return ;
			}	
		}	
		catch(exception e)
		{
			sendBack = true ;
			Database.rollback(sp);
			apexpages.addMessage( new apexpages.Message( apexpages.Severity.error , e.getMessage() ,''  ) );
		}
	}
	public pagereference back()
	{
		return new pagereference('/' + apexpages.currentPage().getParameters().get('id')) ;
	}
	/*
	if (expSheetinfo.OwnerId != userinfo.getUserId())
			{
				apexpages.addMessage( new apexpages.Message( apexpages.Severity.info , 'Your are not authorized to view '+ expSheetinfo.Name , ''  ) );
				return ;	
			}
			else if (expSheetinfo.Status__c == 'Approved')
			{
				apexpages.addMessage( new apexpages.Message( apexpages.Severity.info , 'Expense Sheet '+ expSheetinfo.Name + ' is Already approved' ,'' ) );
				return ;
			}
			else if (expSheetinfo.Status__c == 'Submitted_For_Approval')
			{
				apexpages.addMessage( new apexpages.Message( apexpages.Severity.info , 'Expense Sheet '+ expSheetinfo.Name + ' is Already submitted for approval' , '' ) );
				return ;	
			}
			else
			{
	
	public static TestMethod void submittExpenseSheet()
	{
		
		/*
		User ur = [Select Id , Name , Email From User where Id = '00590000000GMWn'];
		System.runAs(ur)
		{
			Account act = new Account(Name='ABC Company',Type='Supplier');
			insert act;
			Tax_Rate__c tx = new Tax_Rate__c(Name = 'VAT' , Tax_Rate__c = 15 );
			insert tx ;
			Nominal_Categories__c  nc = new Nominal_Categories__c (Name = 'this is test');
			insert nc ; 
			Sub_Category__c sb = new Sub_Category__c(Nominal_Categories__c = nc.Id , Range_To__c = 200, Range_From__c=10, Name = 'testSubcatagories');
			insert sb;
			Nominal_Account__c nm = new Nominal_Account__c (Sub_Category__c = sb.Id , Tax_Rate__c = tx.Id, Expense__c = true, Name = 'Plumbering', Account_Code__c = 150);
			insert nm ;
			Opportunity op = new Opportunity(Name = 'Opportunity abc' , StageName = 'IIT' , Activity_Start__c = date.today(), Activity_End__c = date.today().addDays(5) , CloseDate = date.today().addDays(5));
			insert op;
			Opportunity subOp = new Opportunity(Name = 'Opportunity abc' , StageName = 'IIT' , Activity_Start__c = date.today(), Activity_End__c = date.today().addDays(5) , Sub_Project__c =op.Id , CloseDate = date.today().addDays(5));
			insert subOp;
			Expense_Sheet__c esinfo = new Expense_Sheet__c();
			esinfo.Month_Number__c = date.today().month();
			esinfo.Year__c = date.today().year();
			insert esinfo;
			Expense_Sheet_Detail__c lstExpenseSheetVar = new Expense_Sheet_Detail__c();
			lstExpenseSheetVar.Date__c = date.today();
			lstExpenseSheetVar.Nominal_Account__c = nm.Id;
			lstExpenseSheetVar.Index__c =  0 ;
			lstExpenseSheetVar.Quantity__c =  1 ;
			lstExpenseSheetVar.Narrative__c = 'test Code';
			lstExpenseSheetVar.Total_Net__c = 15 ;
			lstExpenseSheetVar.Total_VAT__c = 2 ;
			lstExpenseSheetVar.Total_Gross__c = 17 ;
			lstExpenseSheetVar.Project__c = op.Id ;
			lstExpenseSheetVar.Expense_Sheet__c = esinfo.Id ;
			insert lstExpenseSheetVar ;
			apexpages.currentPage().getParameters().put('id' , esinfo.Id);
			SubmitExpenseSheetForApproval obj = new SubmitExpenseSheetForApproval();
			obj.submitExpenseSheet();
			obj.back();
			esinfo = new Expense_Sheet__c();
			esinfo.Month_Number__c = date.today().month();
			esinfo.Year__c = date.today().year();
			esinfo.Status__c = 'Submitted_For_Approval';
			insert esinfo;
			apexpages.currentPage().getParameters().put('id' , null);
			obj.submitExpenseSheet();
		}
		
	}
	public static TestMethod void submittExpenseSheetNormalUser()
	{
		
		Account act = new Account(Name='ABC Company',Type='Supplier');
		insert act;
		Tax_Rate__c tx = new Tax_Rate__c(Name = 'VAT' , Tax_Rate__c = 15 );
		insert tx ;
		Nominal_Categories__c  nc = new Nominal_Categories__c (Name = 'this is test');
		insert nc ; 
		Sub_Category__c sb = new Sub_Category__c(Nominal_Categories__c = nc.Id , Range_To__c = 200, Range_From__c=10, Name = 'testSubcatagories');
		insert sb;
		Nominal_Account__c nm = new Nominal_Account__c (Sub_Category__c = sb.Id , Tax_Rate__c = tx.Id, Expense__c = true, Name = 'Plumbering', Account_Code__c = 150);
		insert nm ;
		Opportunity op = new Opportunity(Name = 'Opportunity abc' , StageName = 'IIT' , Activity_Start__c = date.today(), Activity_End__c = date.today().addDays(5) , CloseDate = date.today().addDays(5));
		insert op;
		Opportunity subOp = new Opportunity(Name = 'Opportunity abc' , StageName = 'IIT' , Activity_Start__c = date.today(), Activity_End__c = date.today().addDays(5) , Sub_Project__c =op.Id , CloseDate = date.today().addDays(5));
		insert subOp;
		Expense_Sheet__c esinfo = new Expense_Sheet__c();
		esinfo.Month_Number__c = date.today().month();
		esinfo.Year__c = date.today().year();
		insert esinfo;
		Expense_Sheet_Detail__c lstExpenseSheetVar = new Expense_Sheet_Detail__c();
		lstExpenseSheetVar.Date__c = date.today();
		lstExpenseSheetVar.Nominal_Account__c = nm.Id;
		lstExpenseSheetVar.Quantity__c =  1 ;
		lstExpenseSheetVar.Narrative__c = 'test Code';
		lstExpenseSheetVar.Total_Net__c = 15 ;
		lstExpenseSheetVar.Total_VAT__c = 2 ;
		lstExpenseSheetVar.Total_Gross__c = 17 ;
		lstExpenseSheetVar.Project__c = op.Id ;
		lstExpenseSheetVar.Expense_Sheet__c = esinfo.Id ;
		insert lstExpenseSheetVar ;
		apexpages.currentPage().getParameters().put('id' , esinfo.Id);
		SubmitExpenseSheetForApproval obj = new SubmitExpenseSheetForApproval();
		obj.submitExpenseSheet();
		obj.back();
		esinfo = new Expense_Sheet__c();
		esinfo.Month_Number__c = date.today().month();
		esinfo.Year__c = date.today().year();
		esinfo.Status__c = 'Submitted_For_Approval';
		insert esinfo;
		apexpages.currentPage().getParameters().put('id' , null);
		obj.submitExpenseSheet();
	}
	*/
}