ZumZumFinancials_Dev1/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Nominal_Account__c</fullName>
        <label>Nominal Account</label>
        <referenceTo>Nominal_Account__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Tax_Rate__c</fullName>
        <label>Tax Rate</label>
        <referenceTo>Tax_Rate__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

ZumZumFinancials_Dev1/src/objects/CustomerLookup__c.object
<CustomObject>
    <fields>
        <fullName>Nominal_Account__c</fullName>
        <label>Nominal Account</label>
        <referenceTo>Nominal_Account__c</referenceTo>
        <relationshipLabel>CustomerLookup</relationshipLabel>
        <relationshipName>CustomerLookup</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SupplierAccount__c</fullName>
        <label>SupplierAccount</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>CustomerLookup (AccountSupplier)</relationshipLabel>
        <relationshipName>CustomerLookup1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Tax_Rate__c</fullName>
        <label>Tax_Rate</label>
        <referenceTo>Tax_Rate__c</referenceTo>
        <relationshipLabel>CustomerLookup</relationshipLabel>
        <relationshipName>CustomerLookup</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>CustomerLookup</label>
    <nameField>
        <label>CustomerLookup Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CustomerLookup</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

ZumZumFinancials_Dev1/src/objects/Ledger__c.object
<CustomObject>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount Paid</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Details__c</fullName>
        <label>Details</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Tax_Rate__c</fullName>
        <label>Tax Rate</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Trans_Date__c</fullName>
        <label>Trans Date</label>
        <type>Date</type>
    </fields>
    <label>Ledger</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Ledger Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ledger</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

ZumZumFinancials_Dev1/src/objects/Nominal_Account__c.object
<CustomObject>
    <fields>
        <fullName>Account_Code__c</fullName>
        <label>Account Code</label>
        <precision>4</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Expense__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Expense</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Sub_Category__c</fullName>
        <label>Sub Category</label>
        <referenceTo>Sub_Category__c</referenceTo>
        <relationshipLabel>Nominal Accounts</relationshipLabel>
        <relationshipName>Nominal_Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Tax_Rate__c</fullName>
        <label>Tax Rate</label>
        <referenceTo>Tax_Rate__c</referenceTo>
        <relationshipLabel>Nominal Accounts</relationshipLabel>
        <relationshipName>Nominal_Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Nominal Account</label>
    <nameField>
        <label>Nominal Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Nominal Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

ZumZumFinancials_Dev1/src/objects/Nominal_Categories__c.object
<CustomObject>
    <label>Nominal Category</label>
    <nameField>
        <label>Nominal Categories Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Nominal Categories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

ZumZumFinancials_Dev1/src/objects/Sub_Category__c.object
<CustomObject>
    <fields>
        <fullName>Nominal_Categories__c</fullName>
        <label>Nominal Categories</label>
        <referenceTo>Nominal_Categories__c</referenceTo>
        <relationshipLabel>Sub Category</relationshipLabel>
        <relationshipName>Sub_Category</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Range_From__c</fullName>
        <label>Range From</label>
        <precision>4</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Range_To__c</fullName>
        <label>Range To</label>
        <precision>4</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Sub Category</label>
    <nameField>
        <label>Sub Category Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sub Category</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

ZumZumFinancials_Dev1/src/objects/Tax_Rate__c.object
<CustomObject>
    <fields>
        <fullName>Tax_Rate__c</fullName>
        <label>Tax Rate</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <label>Tax</label>
    <nameField>
        <label>Tax Rate Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tax</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

ZumZumFinancials_Dev1/src/classes/SupplierOpeningBalances.cls
public class SupplierOpeningBalances {	
	public CustomerLookup__c objectAccount{get;set;}
	public Ledger__c objectLedger{get;set;}
	public string BType {get; set;}
	public string retURL{get; set;}
	public string currencySymbol{get;set;}
	public string Amount{get;set;}
	public SupplierOpeningBalances()
	{
		retURL = 'https://'+ApexPages.currentPage().getHeaders().get('Host')+'/apex/Setup';
		currencySymbol = Functions.getOrganisationCurrency('CurrencySymbol');
		objectAccount = new CustomerLookup__c();
		objectLedger = new Ledger__c();
		objectLedger.Trans_Date__c = Date.today();		
		Amount = '0.0';	
	}
	public PageReference Save()
	{
		try
		{
			ValidationRules();
			objectLedger.Amount__c = decimal.valueOf(Amount); 
			string AccountNo = [select AccountNumber from Account where id=: objectAccount.SupplierAccount__c].AccountNumber;		
			string DebitorsCode = Functions.getNominalAccountCode('Suspense Account');
			string CreditorsCode = Functions.getNominalAccountCode('Creditors Control Account');				
			Ledger financial = new Ledger();			
			CustomerRefund_BudgetModel bModel = new CustomerRefund_BudgetModel();
			if(BType == 'Debit')
			{		
				financial.AddDebitOpeningBalances('PI', objectLedger.Amount__c , objectLedger.Details__c,  AccountNo , DebitorsCode ,CreditorsCode, objectLedger.Trans_Date__c);				
				bModel.AddDebit(Functions.getNominalAccountId('Suspense Account') , objectLedger.Amount__c  , string.valueOf(objectLedger.Trans_Date__c));
				bModel.AddCredit(Functions.getNominalAccountId('Creditors Control Account'),objectLedger.Amount__c , string.valueOf(objectLedger.Trans_Date__c)); 			  
			}		
			else
			{		
				financial.AddCreditOpeningBalances('PI', objectLedger.Amount__c , objectLedger.Details__c,  AccountNo ,  DebitorsCode ,CreditorsCode, objectLedger.Trans_Date__c);								
 				bModel.AddDebit(Functions.getNominalAccountId('Creditors Control Account'), objectLedger.Amount__c  , string.valueOf(objectLedger.Trans_Date__c));
 				bModel.AddCredit(Functions.getNominalAccountId('Suspense Account'),objectLedger.Amount__c , string.valueOf(objectLedger.Trans_Date__c));
			}		
		financial.save();				
		bModel.newSave();
		return new PageReference(retURL);
		}
		catch(exception ex)
		{
			apexpages.addMessages(ex);
			return null;
		}
	}
	public void ValidationRules()
	{
		if(objectLedger.Trans_Date__c == null)
			throw new CustomException('You must select a date');
		if(objectAccount.SupplierAccount__c == null)
			throw new CustomException('You must select an Account');			
		if(Amount == null || Amount == '')    	    	
			throw new CustomException('Enter amount first');
		if(!Pattern.matches('^[0-9]+(.[0-9]{1,2})?$', Amount)) 
			throw new CustomException('Enter valid currency value');
		if(decimal.valueOf(Amount) <= 0)    	    	
			throw new CustomException('Enter amount first');
						
	}
	public PageReference SaveAndNew()
	{
		this.save();
		clearAll();		
		return null;
	}
	public PageReference Cancel()
	{		
		return new PageReference(retURL);
	}
	public void clearAll()
	{
		objectLedger.Trans_Date__c = null;
		objectAccount.SupplierAccount__c = null;
		objectLedger.Details__c = null;
		objectLedger.Amount__c = null;		
	}
	private static testMethod void SupplierOpeningBalances_Test()
	{		
		Tax_Rate__c tx = new Tax_Rate__c(Name = 'VAT' , Tax_Rate__c = 15 );
		insert tx ;
    	Nominal_Categories__c  nc = new Nominal_Categories__c (Name = 'this is test');
		insert nc ; 
		Sub_Category__c sb = new Sub_Category__c(Nominal_Categories__c = nc.Id , Range_To__c = 200, Range_From__c=10, Name = 'testSubcatagories');
		insert sb;
		Nominal_Account__c nm = new Nominal_Account__c (Sub_Category__c = sb.Id , Tax_Rate__c = tx.Id, Expense__c = true, Name = 'Plumbering', Account_Code__c = 1222);
		insert nm ;
		Account act = new Account(Name='ABC Company',Type='Supplier', Nominal_Account__c = nm.id);
		insert act;
			
		SupplierOpeningBalances SoB = new SupplierOpeningBalances();
		try
		{
			SoB.ValidationRules();
		}
		catch(exception e)
		{
			system.assertEquals(e.getMessage(),'You must select an Account');
		}
		SoB.objectAccount.SupplierAccount__c = act.id;
		try
		{
			SoB.ValidationRules();
		}
		catch(exception e)
		{
			system.assertEquals(e.getMessage(),'Enter amount first');
		}
		SoB.Amount = 'gafadf';
		try
		{
			SoB.ValidationRules();
		}
		catch(exception e)
		{
			system.assertEquals(e.getMessage(),'Enter valid currency value');
		}
		SoB.Amount = '11';
		SoB.objectLedger.Trans_Date__c = null;
		try
		{
			SoB.ValidationRules();
		}
		catch(exception e)
		{
			system.assertEquals(e.getMessage(),'You must select a date');
		}
		SoB.objectLedger.Trans_Date__c = Date.today();
		SoB.BType = 'Debit';		
		SoB.Save();		
		SoB.BType = 'Credit';
		SoB.SaveAndNew();
		SoB.Cancel();		
	}
}