ZumZumFinancials_Dev1/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Billing_Contact__c</fullName>
        <label>Billing Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

ZumZumFinancials_Dev1/src/objects/Sales_Invoice__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <label>Customer Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Sales Invoices</relationshipLabel>
        <relationshipName>Sales_Invoices</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Invoice_Due_Date__c</fullName>
        <label>Invoice Due Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Paid__c</fullName>
        <defaultValue>&apos;N&apos;</defaultValue>
        <label>Paid</label>
        <length>1</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Posted</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Sales Invoice</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sales Credit</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Sales Invoice</label>
    <nameField>
        <label>SI Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Invoices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

ZumZumFinancials_Dev1/src/objects/Schedule_Reminders__c.object
<CustomObject>
    <fields>
        <fullName>EmailTemplateId__c</fullName>
        <label>EmailTemplateId</label>
        <length>225</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Frequency__c</fullName>
        <label>Frequency</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Reminder_Criteria__c</fullName>
        <label>Reminder Criteria</label>
        <picklist>
            <picklistValues>
                <fullName>Before Invoice Due Date</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>After Invoice Due Date</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>zero_val__c</fullName>
        <defaultValue>false</defaultValue>
        <label>zero_val</label>
        <type>Checkbox</type>
    </fields>
    <label>Schedule Reminders</label>
    <nameField>
        <label>Schedule Reminders Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Schedule Reminders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

ZumZumFinancials_Dev1/src/classes/ReminderBatchEmails.cls
global class ReminderBatchEmails implements Database.batchable<sObject>
{
	global Map<date,Id> dueDateTemplateIdMap;
	
	global ReminderBatchEmails(Map<date,Id> templateMap)
	{
		dueDateTemplateIdMap = templateMap;
	}
	
	global Database.QueryLocator Start(Database.BatchableContext bc)
	{
		set<Date> dateSet = dueDateTemplateIdMap.keySet();
		string str = '';
		for(Date s : DateSet)
		{
			str +=','+s.format();
		}
		//throw new customException('dateSet str= '+str);
		
		return  Database.GetQueryLocator([Select Id,Billing_Contact__c,
										  (Select Id, Name, Invoice_Due_Date__c, Type__c, Status__c From Sales_Invoices__r Where Invoice_Due_Date__c in : dateSet and Paid__c='N') 
										  From Account 
										  Where Id in 
										  (
											Select s.Account__c 
											From Sales_Invoice__c s
											Where s.Invoice_Due_Date__c in : dateSet 
											and Paid__c='N'
										  ) and Billing_Contact__c != null]);		
	}
	
	global void Execute(Database.BatchableContext bc, List<SObject> scope)
	{		
		Messaging.SingleEmailMessage[] mailingList = new Messaging.SingleEmailMessage[]{};
		Map<Id, Set<Date>> accountInvoiceDates = new Map<Id, Set<Date>>();
		for(Account acc : (List<Account>) scope)
        {        	
        	Set<Date> dateSet = new Set<Date>();
        	for(Sales_Invoice__c si : acc.Sales_Invoices__r)
        	{        		
        		dateSet.add(si.Invoice_Due_Date__c);
        	}
        	for(Date d : dateSet)
        	{        		
        		Messaging.SingleEmailMessage mail = new Messaging.singleEmailMessage();        
		        mail.setTargetObjectId(acc.Billing_Contact__c);
		        system.debug('billing contact :'+acc.Billing_Contact__c);
		        mail.setWhatId(acc.Id);
				// here i gave the id of the email template to be executed by this class
		        mail.setTemplateId(dueDateTemplateIdMap.get(d));
		        system.debug('billing contact :'+dueDateTemplateIdMap.get(d));                       
		        mail.setBccSender(false);
		        mail.setUseSignature(false);
		        mail.setSenderDisplayName(System.UserInfo.GetName());
		        mail.setSaveAsActivity(false);
		        mailingList.add(mail);	        		
        	}           
        }
        Messaging.sendEmail(mailingList);
	}
	
	global void Finish(Database.BatchableContext bc)
	{		
	}	
	private static testMethod void ReminderBatchEmails_Test()
	{
		EmailTemplate lstEml = [Select Id, Name From EmailTemplate where Folder.DeveloperName = 'Invoice_Reminders'];
		Schedule_Reminders__c srObj = new Schedule_Reminders__c(Frequency__c = 2, Reminder_Criteria__c = 'Before Invoice Due Date' , EmailTemplateId__c = lstEml.id , zero_val__c = true);
		insert srObj;
		Map<Date, Id> invTmplt = new Map<Date, Id>();
		set<Date> ds = new set<Date>();		
		ds.add(Date.today());
		invTmplt.put(Date.newInstance(2011,7,19),srObj.EmailTemplateId__c);
		
		ReminderBatchEmails obj = new ReminderBatchEmails(invTmplt);
		
		obj.dueDateTemplateIdMap = invTmplt;
		Database.BatchableContext b;
				
		obj.Start(b);
		
		
		set<Date> dateSet = obj.dueDateTemplateIdMap.keySet();
		string str = '';
		for(Date s : DateSet)
		{
			str +=','+s.format();
		}
		
		List<SObject> lstAct = [Select Id,Billing_Contact__c,
										  (Select Id, Name, Invoice_Due_Date__c, Type__c, Status__c From Sales_Invoices__r Where Invoice_Due_Date__c in : dateSet and Paid__c='N') 
										  From Account 
										  Where Id in 
										  (
											Select s.Account__c 
											From Sales_Invoice__c s
											Where s.Invoice_Due_Date__c in : dateSet 
											and Paid__c='N'
										  ) and Billing_Contact__c != null limit 100];										  
		
		
		obj.Execute(b, lstAct);
		
		obj.Finish(b);
		
	}  
}