ZumZumFinancials_Dev1/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Tax_Rate__c</fullName>
        <label>Tax Rate</label>
        <referenceTo>Tax_Rate__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

ZumZumFinancials_Dev1/src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Activity_End__c</fullName>
        <defaultValue>today()+365</defaultValue>
        <description>Expected activity end date, may post date eligibility end date</description>
        <inlineHelpText>Enter the expected activity end date, may post date eligibility end date</inlineHelpText>
        <label>Activity End</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Activity_Start__c</fullName>
        <defaultValue>today()</defaultValue>
        <description>Expected activity start date, may pre-date eligibility start date</description>
        <inlineHelpText>Enter the expected activity start date, may pre-date eligibility start date</inlineHelpText>
        <label>Activity Start</label>
        <type>Date</type>
    </fields>
</CustomObject>

ZumZumFinancials_Dev1/src/objects/Sales_Order__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <label>Customer Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Sales Orders</relationshipLabel>
        <relationshipName>Sales_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Order_By__c</fullName>
        <label>Order By</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Sales_Orders2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Order_Date__c</fullName>
        <label>Order Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending</fullName>
                <default>true</default>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Sales Order</label>
    <nameField>
        <label>Order No.</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

ZumZumFinancials_Dev1/src/objects/Sales_Order_Line_Items__c.object
<CustomObject>
    <fields>
        <fullName>Sales_Order__c</fullName>
        <label>Sales Order</label>
        <referenceTo>Sales_Order__c</referenceTo>
        <relationshipLabel>Sales Order Line Items</relationshipLabel>
        <relationshipName>Sales_Order_Line_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Tax_Rate__c</fullName>
        <label>Tax Rate</label>
        <referenceTo>Tax_Rate__c</referenceTo>
        <relationshipLabel>Sales Order Line Items</relationshipLabel>
        <relationshipName>Sales_Order_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Sales Order Line Items</label>
    <nameField>
        <label>Sales Order Line Items Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Order Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

ZumZumFinancials_Dev1/src/objects/Tax_Rate__c.object
<CustomObject>
    <fields>
        <fullName>Tax_Rate__c</fullName>
        <label>Tax Rate</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <label>Tax</label>
    <nameField>
        <label>Tax Rate Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tax</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

ZumZumFinancials_Dev1/src/classes/InvalidOperationSO.cls
public class InvalidOperationSO 
{
	public Sales_Order__c sO {get; set;}
	public InvalidOperationSO( apexpages.Standardcontroller invalidOperation )
	{
	
	}
	public pagereference init()
	{
		try
		{
			Id editId = apexpages.currentPage().getParameters().get('id');
			sO = [select id , Name ,Status__c  from Sales_Order__c where Id IN(Select Sales_Order__c from Sales_Order_Line_Items__c where Id = :editId ) limit 1 ];
			return new pagereference('/apex/EditSalesOrder?id='+sO.Id+'&retURL='+apexpages.currentPage().getParameters().get('retURL'));
		}
		catch(Exception e)
		{
			apexpages.addMessages(e);	
			return null ;
		}
	}
	public static TestMethod void testDeleteSalesOrder()
	{
		//preparing data for unit testing
		Tax_Rate__c tx = new Tax_Rate__c(Name = 'VAT' , Tax_Rate__c = 15 );
		insert tx ;
		Account act = new Account(Name='ABC Company',Type='Customer' , Tax_Rate__c = tx.Id );
		insert act;
		
		Opportunity op = new Opportunity(AccountId = act.id , Name = 'Opportunity abc' , StageName = 'IIT' , Activity_Start__c = date.today(), Activity_End__c = date.today().addDays(5) , CloseDate = date.today().addDays(5));
		insert op;
		
		Sales_Order__c sO = new Sales_Order__c ();
		sO.Account__c = act.id;
		sO.Name = '000';
		sO.Order_By__c = userinfo.getUserId();
		sO.Order_Date__c = date.today();
		sO.Status__c = 'Approved';
		
		insert sO ;
		
		apexpages.currentPage().getParameters().put('id' , sO.Id);
		ApexPages.Standardcontroller std = new ApexPages.Standardcontroller(sO);
		InvalidOperationSO obj = new  InvalidOperationSO(std); 
		obj.init();
	}
	
}