ZumZumFinancials_Dev1/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Country__c</fullName>
        <label>ECSL Region</label>
        <picklist>
            <picklistValues>
                <fullName>ETHIOPIA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AFGHANISTAN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ÅLAND ISLANDS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ALBANIA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ALGERIA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AMERICAN SAMOA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ANDORRA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ANGOLA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ANGUILLA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ANTARCTICA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ANTIGUA AND BARBUDA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ARGENTINA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ARMENIA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ARUBA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AUSTRALIA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AUSTRIA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AZERBAIJAN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BAHAMAS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BAHRAIN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BANGLADESH</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BARBADOS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BELARUS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BELGIUM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BELIZE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BENIN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BERMUDA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BHUTAN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BOLIVIA, PLURINATIONAL STATE OF</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BONAIRE, SINT EUSTATIUS AND SABA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BOSNIA AND HERZEGOVINA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>UNITED KINGDOM</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Credit__c</fullName>
        <defaultValue>0.00</defaultValue>
        <label>Credit</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Debit__c</fullName>
        <defaultValue>0.00</defaultValue>
        <label>Debit</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
</CustomObject>

ZumZumFinancials_Dev1/src/objects/Schedule_Statements__c.object
<CustomObject>
    <fields>
        <fullName>Day__c</fullName>
        <label>Day</label>
        <picklist>
            <picklistValues>
                <fullName>1</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>6</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>7</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>8</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>9</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>10</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>11</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>12</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>13</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>14</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>15</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>16</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>17</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>18</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>19</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>20</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>21</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>22</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>23</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>24</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>25</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>26</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>27</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>28</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>29</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>30</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Frequency__c</fullName>
        <label>Frequency</label>
        <picklist>
            <picklistValues>
                <fullName>Monthly</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Yearly</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Month__c</fullName>
        <label>Month</label>
        <picklist>
            <picklistValues>
                <fullName>1</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>6</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>7</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>8</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>9</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>10</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>11</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>12</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>send_statements_if_balance_is_zero__c</fullName>
        <defaultValue>false</defaultValue>
        <label>send statements if balance is zero</label>
        <type>Checkbox</type>
    </fields>
    <label>Schedule Statements</label>
    <nameField>
        <label>Schedule Statements Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Schedule Statements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

ZumZumFinancials_Dev1/src/classes/ScheduledStatements.cls
global class ScheduledStatements implements Schedulable
{
	public ScheduledStatements()
	{
		
	}
	
	global void Execute(SchedulableContext sc)
	{
		List<Schedule_Statements__c> schList = [select id, send_statements_if_balance_is_zero__c from Schedule_Statements__c where (Day__c=:string.valueof(date.today().day()) and Frequency__c='Monthly') or (Day__c=:string.valueof(date.Today().Month()) and Month__c=:string.valueof(date.Today().Month()) and Frequency__c='Yearly') order by Month__c desc limit 1];
		if(schList.Size()>0)
		{
			boolean nonZeroBalance = schList[0].send_statements_if_balance_is_zero__c; 	
			List<AsyncApexJob> lst = [Select a.TotalJobItems, a.Status, a.JobType, a.JobItemsProcessed, a.Id, a.ApexClass.Name, a.ApexClassId From AsyncApexJob a Where Status in ('Processing','Queued') and JobType='BatchApex'];
    		if(lst.size()<5)
    		{
    			StatementsBatchEmails obj = new StatementsBatchEmails(nonZeroBalance);
				database.ExecuteBatch(obj,100);	
    		}
    		else
    		{
    			User u = [select Email from User where Id=:UserInfo.getUserId()];
    			Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage(); //instantiate a new message object
				String[] toAddresses = new String[] {u.Email}; //denote the email address for receiving the message
				mail.setToAddresses(toAddresses); //to
				mail.setSubject('Scheduled Statements Failed Due to inavailability of batch job slot.'); //subject
				mail.setPlainTextBody('Scheduled Statements Failed Due to inavailability of batch job slot.'); //body
				Messaging.sendEmail(new Messaging.SingleEmailMessage[] { mail }); //send
    		}			
		}	
	}
	
	
	// start of test functions
	private static TestMethod void statusChecker()
	{
		
		Account act = new Account(Name='ABC Company',Type='Supplier' , AccountNumber = 'SCTEST' , Credit__c = 500 , Debit__c = 100 , Country__c = 'UNITED KINGDOM' );
		insert act;
		
		Contact cT = new Contact(Email= 'test@test.com', Description = 'This is test Contact', Department = 'ZumZum' , AccountId = act.Id , LastName = 'TEST');
		insert cT ;
		
		List<Schedule_Statements__c> SStatments = new List<Schedule_Statements__c>();
		SStatments.add(new Schedule_Statements__c(Day__c = string.valueof(date.today().day()) ,
																		Frequency__c = 'Monthly ',
																		Month__c = string.valueof(date.Today().Month()) ,
																		send_statements_if_balance_is_zero__c = true
																		 ))	;
																		 
		SStatments.add(new Schedule_Statements__c(Day__c = string.valueof(date.today().day()) ,
																		Frequency__c = 'Yearly ',
																		Month__c = string.valueof(date.Today().Month()) ,
																		send_statements_if_balance_is_zero__c = true
																		 ))	;
																		 																		 
		insert 	SStatments ;
		
		String CRON_EXP = '0 5 * * * ?'; 
		String jobId = System.schedule('testBasicScheduledApex',CRON_EXP, new ScheduledStatements());
		ScheduledStatements obj = new ScheduledStatements();
		obj.Execute(null);
		
		
		/*jobId = System.schedule('testBasicScheduledApex1',CRON_EXP, new ScheduledStatements());
		jobId = System.schedule('testBasicScheduledApex2',CRON_EXP, new ScheduledStatements());
		jobId = System.schedule('testBasicScheduledApex3',CRON_EXP, new ScheduledStatements());
		jobId = System.schedule('testBasicScheduledApex4',CRON_EXP, new ScheduledStatements());
		jobId = System.schedule('testBasicScheduledApex5',CRON_EXP, new ScheduledStatements());
		jobId = System.schedule('testBasicScheduledApex6',CRON_EXP, new ScheduledStatements());
		jobId = System.schedule('testBasicScheduledApex7',CRON_EXP, new ScheduledStatements());
		jobId = System.schedule('testBasicScheduledApex8',CRON_EXP, new ScheduledStatements());
		obj.Execute(null);
		*/
	}
	
	// end of test functions
}