ZumZumFinancials_Dev1/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Nominal_Account__c</fullName>
        <label>Nominal Account</label>
        <referenceTo>Nominal_Account__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Tax_Rate__c</fullName>
        <label>Tax Rate</label>
        <referenceTo>Tax_Rate__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

ZumZumFinancials_Dev1/src/objects/Bank_Account__c.object
<CustomObject>
    <fields>
        <fullName>Account_Number__c</fullName>
        <externalId>true</externalId>
        <label>Account Number</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Nominal_Account__c</fullName>
        <label>Nominal Account</label>
        <referenceTo>Nominal_Account__c</referenceTo>
        <relationshipLabel>Bank Accounts</relationshipLabel>
        <relationshipName>Bank_Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Draft</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Deleted</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Bank Account</label>
    <nameField>
        <label>Bank Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bank Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

ZumZumFinancials_Dev1/src/objects/Control_Account__c.object
<CustomObject>
    <fields>
        <fullName>Default_Bank__c</fullName>
        <label>Default Bank</label>
        <referenceTo>Nominal_Account__c</referenceTo>
        <relationshipLabel>Control Accounts (Default Bank)</relationshipLabel>
        <relationshipName>Default_Bank</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Nominal_Account__c</fullName>
        <label>Nominal Account</label>
        <referenceTo>Nominal_Account__c</referenceTo>
        <relationshipLabel>Control Accounts</relationshipLabel>
        <relationshipName>Control_Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Control Account</label>
    <nameField>
        <label>Control Accounts</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Control Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

ZumZumFinancials_Dev1/src/objects/CustomerLookup__c.object
<CustomObject>
    <fields>
        <fullName>CustomerAccount__c</fullName>
        <label>CustomerAccount</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>CustomerLookup</relationshipLabel>
        <relationshipName>CustomerLookup</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Date__c</fullName>
        <label>Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Nominal_Account__c</fullName>
        <label>Nominal Account</label>
        <referenceTo>Nominal_Account__c</referenceTo>
        <relationshipLabel>CustomerLookup</relationshipLabel>
        <relationshipName>CustomerLookup</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SupplierAccount__c</fullName>
        <label>SupplierAccount</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>CustomerLookup (AccountSupplier)</relationshipLabel>
        <relationshipName>CustomerLookup1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Tax_Rate__c</fullName>
        <label>Tax_Rate</label>
        <referenceTo>Tax_Rate__c</referenceTo>
        <relationshipLabel>CustomerLookup</relationshipLabel>
        <relationshipName>CustomerLookup</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>CustomerLookup</label>
    <nameField>
        <label>CustomerLookup Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CustomerLookup</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

ZumZumFinancials_Dev1/src/objects/Nominal_Account__c.object
<CustomObject>
    <fields>
        <fullName>Account_Code__c</fullName>
        <label>Account Code</label>
        <precision>4</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Expense__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Expense</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Nominal_Code__c</fullName>
        <formula>TEXT( Account_Code__c )</formula>
        <label>Nominal Code</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sub_Category__c</fullName>
        <label>Sub Category</label>
        <referenceTo>Sub_Category__c</referenceTo>
        <relationshipLabel>Nominal Accounts</relationshipLabel>
        <relationshipName>Nominal_Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Tax_Rate__c</fullName>
        <label>Tax Rate</label>
        <referenceTo>Tax_Rate__c</referenceTo>
        <relationshipLabel>Nominal Accounts</relationshipLabel>
        <relationshipName>Nominal_Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Nominal Account</label>
    <nameField>
        <label>Nominal Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Nominal Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

ZumZumFinancials_Dev1/src/objects/Nominal_Categories__c.object
<CustomObject>
    <label>Nominal Category</label>
    <nameField>
        <label>Nominal Categories Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Nominal Categories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

ZumZumFinancials_Dev1/src/objects/Sub_Category__c.object
<CustomObject>
    <fields>
        <fullName>Nominal_Categories__c</fullName>
        <label>Nominal Categories</label>
        <referenceTo>Nominal_Categories__c</referenceTo>
        <relationshipLabel>Sub Category</relationshipLabel>
        <relationshipName>Sub_Category</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Range_From__c</fullName>
        <label>Range From</label>
        <precision>4</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Range_To__c</fullName>
        <label>Range To</label>
        <precision>4</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Sub Category</label>
    <nameField>
        <label>Sub Category Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sub Category</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

ZumZumFinancials_Dev1/src/objects/Tax_Rate__c.object
<CustomObject>
    <fields>
        <fullName>Tax_Rate__c</fullName>
        <label>Tax Rate</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <label>Tax</label>
    <nameField>
        <label>Tax Rate Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tax</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

ZumZumFinancials_Dev1/src/classes/controllerSupplierRefund.cls
public class controllerSupplierRefund {
public CustomerLookup__c objectLookup{get;set;}
public Control_Account__c defaultBank{get;set;}
public string NominalId{get;set;}
public Nominal_Account__c Creditors;
public string cheque{get;set;}
public string pay{get;set;}
public list<Bank_Account__c> listBankAccount {get;set;}
public string retURL{get;set;}
public string currencySymbol{get;set;}
public Ledger financial;
public boolean modifiedCredit = false;
public boolean modifiedDebit = false;
	public controllerSupplierRefund()
	{
		try
		{	
			pay = '0.0';
			currencySymbol = Functions.getOrganisationCurrency('CurrencySymbol');
			retURL = 'https://'+ApexPages.currentPage().getHeaders().get('Host')+'/apex/TransactionsMenu';									
			objectLookup = new CustomerLookup__c();
			objectLookup.Date__c = Date.today(); 									 																						
			listBankAccount = [select id,Name, Nominal_Account__r.Nominal_Code__c, Nominal_Account__r.Name from Bank_Account__c where Status__c =: 'Active'  order by Nominal_Account__r.Nominal_Code__c];
		}
		catch(exception e)
		{
			apexPages.addMessages(e);
		}						
	}	
	public list<SelectOption> getBankAccount()//options from list of Bank Accounts with Nominal Codes
	{
		try
		{
			List<SelectOption> options = new list<SelectOption>();	
			defaultBank = [Select c.Default_Bank__r.Nominal_Code__c, c.Default_Bank__r.Name, c.Default_Bank__r.Id, c.Default_Bank__c From Control_Account__c c where c.Name= 'Control Accounts'];
			Bank_Account__c opt = [select Name, Nominal_Account__r.Id,Nominal_Account__r.Nominal_Code__c, Nominal_Account__r.Name from Bank_Account__c where Nominal_Account__r.Name =: defaultBank.Default_Bank__r.Name];		
	 		options.add(new SelectOption(opt.Nominal_Account__r.Id,opt.Nominal_Account__r.Nominal_Code__c+' - '+opt.Name));
			for(Bank_Account__c bnk : listBankAccount) 		
			{			
				if(bnk.Nominal_Account__r.id != opt.Nominal_Account__r.Id)
					options.add(new SelectOption(bnk.Nominal_Account__r.Id,bnk.Nominal_Account__r.Nominal_Code__c+' - '+bnk.Name));
			}
			return options;	
		}
		catch(exception e)
		{
			apexpages.addMessages(e);
			return null;
		}
	}
	public PageReference Save()
	{
			try
			{			
			validationRules();
			
 			CustomerRefund_BudgetModel bModel = new CustomerRefund_BudgetModel();
 			bModel.AddDebit(NominalId,decimal.valueOf(pay),string.valueOf(objectLookup.Date__c));
 			bModel.AddCredit(Functions.getNominalAccountId('Creditors Control Account'), decimal.valueOf(pay) , string.valueOf(objectLookup.Date__c));
 			bModel.newSave();
 			 				 			 												
			Ledger financial = new Ledger();
			financial.AddSupplierRefund(decimal.valueOf(pay),Functions.getAccountNumberById(objectLookup.SupplierAccount__c),Functions.getNominalAccountCode('Creditors Control Account'),Functions.getAccountCodeById(NominalId),cheque,objectLookup.Date__c);
			financial.Save();
						
			return new PageReference(retURL);
		}
		catch(exception e)
		{
			ApexPages.addMessages(e);
			return null; 
		}
	}
	public PageReference Cancel()
	{
		return new PageReference(retURL);
	}	
	public void validationRules()
	{		
		if(objectLookup.SupplierAccount__c == null)
			throw new CustomException('Select an account first');
		if(objectLookup.Date__c == null)			
			throw new CustomException('You must enter date to save the record');
		if(pay == null ||pay == '')
			throw new CustomException('Enter an amount first');
		if(!Pattern.matches('^[0-9]+(.[0-9]{1,2})?$', Pay))
			throw new CustomException('Enter valid currency value');
		if(decimal.valueOf(pay) <= 0.0)
			throw new CustomException('Enter an amount first');		
	}
	private static testMethod void controllerCustomerRefundTest()
	{
		Account act = new Account(Name='ABC Company',Type='Supplier');
		insert act;
		Tax_Rate__c tx = new Tax_Rate__c(Name = 'VAT' , Tax_Rate__c = 15 );
		insert tx ;
		//Tax_Rate__c tx = [select Id , Tax_Rate__c from Tax_Rate__c limit 1];
		Nominal_Categories__c  nc = new Nominal_Categories__c (Name = 'this is test');
		insert nc ; 
		Sub_Category__c sb = new Sub_Category__c(Nominal_Categories__c = nc.Id , Range_To__c = 200, Range_From__c=10, Name = 'testSubcatagories');
		insert sb;
		Nominal_Account__c nm = new Nominal_Account__c (Sub_Category__c = sb.Id , Tax_Rate__c = tx.Id, Expense__c = true, Name = 'Plumbering', Account_Code__c = 1222);
		insert nm ;		
		Bank_Account__c ba ;
		try
		{
			ba = new Bank_Account__c (Name = 'testBank',Account_Number__c = 'tst123',Nominal_Account__c = nm.id, Status__c = 'Active');	
			insert ba;
		}
		catch(exception e)
		{
			system.debug('error : '+e.getMessage());
		}		
		controllerSupplierRefund splr = new controllerSupplierRefund();
		splr.objectLookup.CustomerAccount__c = null;
		splr.objectLookup.Date__c = date.today();
		splr.pay = string.valueOf(2);				
		try
		{
			splr.validationRules();
		}
		catch(exception e)
		{
			system.assertEquals(e.getMessage(), 'Select an account first');
		}		
		list<selectoption> getbnkAcctts = splr.getBankAccount();
		splr.NominalId = nm.id;
		splr.objectLookup.SupplierAccount__c = act.id;
		splr.objectLookup.Date__c = null;
		splr.pay = string.valueOf(2);		
		try
		{
			splr.validationRules();
		}
		catch(exception e)
		{
			system.assertEquals(e.getMessage(), 'You must enter date to save the record');
		}		
		splr.objectLookup.CustomerAccount__c = act.id;
		splr.objectLookup.Date__c = Date.today();
		splr.pay = 'a';		
		try
		{
			splr.validationRules();
		}
		catch(exception e)
		{
			system.assertEquals(e.getMessage(), 'Enter valid currency value');
		}
		
		splr.objectLookup.CustomerAccount__c = act.id;
		splr.objectLookup.Date__c = Date.today();
		splr.pay = string.valueOf(0);		
		try
		{
			splr.validationRules();
		} 
		catch(exception e)
		{
			system.assertEquals(e.getMessage(), 'Enter an amount first');
		}
		splr.objectLookup.CustomerAccount__c = act.id;
		splr.objectLookup.Date__c = Date.today();
		splr.pay = null;		
		try
		{
			splr.validationRules();
		}
		catch(exception e)
		{
			system.assertEquals(e.getMessage(), 'Enter an amount first');
		}
		splr.objectLookup.CustomerAccount__c = act.id;
		splr.objectLookup.Date__c = Date.today();
		splr.pay = string.valueOf(2);
		splr.cheque = 'abc';		
		splr.Save();
		splr.Cancel();	
	}
}