ZumZumFinancials_Dev1/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Nominal_Account__c</fullName>
        <label>Nominal Account</label>
        <referenceTo>Nominal_Account__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Tax_Rate__c</fullName>
        <label>Tax Rate</label>
        <referenceTo>Tax_Rate__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

ZumZumFinancials_Dev1/src/objects/Bank_Account__c.object
<CustomObject>
    <fields>
        <fullName>Nominal_Account__c</fullName>
        <label>Nominal Account</label>
        <referenceTo>Nominal_Account__c</referenceTo>
        <relationshipLabel>Bank Accounts</relationshipLabel>
        <relationshipName>Bank_Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Draft</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Deleted</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Bank Account</label>
    <nameField>
        <label>Bank Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bank Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

ZumZumFinancials_Dev1/src/objects/Control_Account__c.object
<CustomObject>
    <fields>
        <fullName>Default_Bank__c</fullName>
        <label>Default Bank</label>
        <referenceTo>Nominal_Account__c</referenceTo>
        <relationshipLabel>Control Accounts (Default Bank)</relationshipLabel>
        <relationshipName>Default_Bank</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Nominal_Account__c</fullName>
        <label>Nominal Account</label>
        <referenceTo>Nominal_Account__c</referenceTo>
        <relationshipLabel>Control Accounts</relationshipLabel>
        <relationshipName>Control_Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Control Account</label>
    <nameField>
        <label>Control Accounts</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Control Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

ZumZumFinancials_Dev1/src/objects/Nominal_Account__c.object
<CustomObject>
    <fields>
        <fullName>Nominal_Code__c</fullName>
        <formula>TEXT( Account_Code__c )</formula>
        <label>Nominal Code</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Tax_Rate__c</fullName>
        <label>Tax Rate</label>
        <referenceTo>Tax_Rate__c</referenceTo>
        <relationshipLabel>Nominal Accounts</relationshipLabel>
        <relationshipName>Nominal_Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Nominal Account</label>
    <nameField>
        <label>Nominal Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Nominal Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

ZumZumFinancials_Dev1/src/objects/RecurringTransaction__c.object
<CustomObject>
    <description>Made by BOSS</description>
    <fields>
        <fullName>Bank_Account__c</fullName>
        <label>Bank Account</label>
        <referenceTo>Bank_Account__c</referenceTo>
        <relationshipLabel>RecurringTransaction</relationshipLabel>
        <relationshipName>RecurringTransaction</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Details__c</fullName>
        <label>Details</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Finish_Date__c</fullName>
        <label>Finish Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Last_Posted__c</fullName>
        <label>Last Posted</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Name_of__c</fullName>
        <label>Frequency Period</label>
        <picklist>
            <picklistValues>
                <fullName>Day(s)</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Week(s)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Month(s)</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Net_Amount__c</fullName>
        <label>Net Amount</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Next_Transaction_Date__c</fullName>
        <label>Next Transaction Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>No_of__c</fullName>
        <label>Frequency</label>
        <precision>2</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Nominal_Account__c</fullName>
        <label>Nominal Account</label>
        <referenceTo>Nominal_Account__c</referenceTo>
        <relationshipLabel>RecurringTransaction</relationshipLabel>
        <relationshipName>RecurringTransaction</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Reference__c</fullName>
        <label>Reference</label>
        <length>225</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Required_Posting__c</fullName>
        <label>Required Posting</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Suspend_Posting__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Suspend Posting</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Tax_Rate__c</fullName>
        <label>Tax Rate</label>
        <referenceTo>Tax_Rate__c</referenceTo>
        <relationshipLabel>RecurringTransaction</relationshipLabel>
        <relationshipName>RecurringTransaction</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>TransactionType__c</fullName>
        <label>Transaction Type</label>
        <picklist>
            <picklistValues>
                <fullName>Bank/Cash/Credit Card Payment</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Bank/Cash/Credit Card Receipt</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bank/Cash/Credit Card Transfer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Customer payment on Account</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>VAT__c</fullName>
        <label>VAT Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>RecurringTransaction</label>
    <nameField>
        <label>Recurring Transaction Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RecurringTransaction</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

ZumZumFinancials_Dev1/src/objects/Tax_Rate__c.object
<CustomObject>
    <fields>
        <fullName>Tax_Rate__c</fullName>
        <label>Tax Rate</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>is_default__c</fullName>
        <defaultValue>false</defaultValue>
        <label>is default</label>
        <type>Checkbox</type>
    </fields>
    <label>Tax</label>
    <nameField>
        <label>Tax Rate Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tax</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

ZumZumFinancials_Dev1/src/classes/controllerRecurringTransaction.cls
public class controllerRecurringTransaction { 
	public RecurringTransaction__c objectRecurringTransaction {get;set;}
	public RecurringTransaction__c editRecurringTransaction {get;set;}	
	public List<Bank_Account__c> listBankAccount{get;set;}
	public List<Tax_Rate__c> listTaxRate{get;set;}
	public string idNom{get;set;}
	public string retURL{get;set;}	
	public string frequency{get;set;}
	public string netAmount{get;set;}
	public string dt  {get;set;}
	public id editID {get;set;}		
	public controllerRecurringTransaction(ApexPages.Standardcontroller std)
	{
		retURL='https://'+apexPages.currentPage().getHeaders().get('Host')+'/apex/BankMenu';
		editId = ApexPages.currentPage().getParameters().get('id');
		if(editId != null)
		{
			objectRecurringTransaction = [select Bank_Account__c,Details__c,Finish_Date__c,No_of__c,Name_of__c,Last_Posted__c,Net_Amount__c,Nominal_Account__c,Reference__c,Required_Posting__c,Start_Date__c,Suspend_Posting__c,Tax_Rate__c,TransactionType__c,VAT__c from RecurringTransaction__c where id=: editId];
			frequency = string.valueOf(objectRecurringTransaction.No_of__c);
			netAmount = string.valueOf(objectRecurringTransaction.Net_Amount__c);
		} 
		else 
			objectRecurringTransaction = new RecurringTransaction__c();
		frequency = '1';
		netAmount = '0.0';
		objectRecurringTransaction.Required_Posting__c = 1;
		objectRecurringTransaction.VAT__c = 0.0;
		objectRecurringTransaction.Start_Date__c = Date.today();
		objectRecurringTransaction.Finish_Date__c = Date.today(); 
		listBankAccount = [select id, Name, Nominal_Account__r.Nominal_Code__c, Nominal_Account__c from Bank_Account__c where Status__c =: 'Active'];
		listTaxRate = [select id, Name, Tax_Rate__c from Tax_Rate__c limit 1000];			
	}
	public controllerRecurringTransaction(RecurringTransaction__c trans)
	{
		objectRecurringTransaction = trans;
	}
	public List<SelectOption> getBankAccount()
	{
		List<SelectOption> options = new list<SelectOption>();				
		Control_Account__c defaultBank = [Select c.Default_Bank__r.Nominal_Code__c, c.Default_Bank__r.Name, c.Default_Bank__r.Id, c.Default_Bank__c From Control_Account__c c where c.Name= 'Control Accounts'];
		Bank_Account__c opt = [select id, Name, Nominal_Account__r.Id,Nominal_Account__r.Nominal_Code__c, Nominal_Account__r.Name from Bank_Account__c where Nominal_Account__r.Name =: defaultBank.Default_Bank__r.Name];
 		options.add(new SelectOption(opt.Id,opt.Nominal_Account__r.Nominal_Code__c+' - '+opt.Name));
		for(Bank_Account__c bnk : listBankAccount) 		
		{			
			if(bnk.Nominal_Account__r.id != opt.Nominal_Account__r.Id)
				options.add(new SelectOption(bnk.Id,bnk.Nominal_Account__r.Nominal_Code__c+' - '+bnk.Name));
		}
		return options;	
	}
	public List<SelectOption> getTaxRate()
	{
		List<SelectOption> options = new List<SelectOption>();
		Tax_Rate__c opt = [select Id, Name, Tax_Rate__c from Tax_Rate__c where is_default__c =: true];
    	options.add(new SelectOption(opt.id,opt.Name));
		for(Tax_Rate__c tx : listTaxRate)
		{
			if(tx.id != opt.id)
				options.add(new SelectOption(tx.id,tx.Name));
		} 
		return options;
	}
	public PageReference Cancel()
	{
		if(editId != null)
		 return new PageReference('/'+editID);
		else
			return new PageReference(retURL);
	}
	public PageReference Save()
	{
		try
		{									
			if(idNom != null && idNom != '')
				objectRecurringTransaction.Nominal_Account__c = idNom;
			SetTaxValues(); 
			if(!Pattern.matches('^[0-9]+$', frequency))
				throw new CustomException('Enter Numeric value');	
			if(!Pattern.matches('^[0-9]+(.[0-9]{1,2})?$', netAmount))
				throw new CustomException('Enter currency value');
			objectRecurringTransaction.No_of__c = decimal.valueOf(frequency);			
			objectRecurringTransaction.Net_Amount__c = decimal.valueOf(netAmount);
			SetNextRunDate(objectRecurringTransaction);			
			BankRecurringModel bnk = new BankRecurringModel(objectRecurringTransaction);
			bnk.Save();	
			return new PageReference('/'+bnk.objRecurringTransaction.id);
		}
		catch(exception e)
		{			
			ApexPages.AddMessages(e);						
			return null;
		} 
	}
	public void SetTaxValues()
	{
		if((objectRecurringTransaction.TransactionType__c == 'Bank/Cash/Credit Card Transfer') ||(objectRecurringTransaction.TransactionType__c == 'Customer payment on Account'))
		{		
			objectRecurringTransaction.Tax_Rate__c = null;
			objectRecurringTransaction.VAT__c = 0.0;			
		}			
	}
	public static void SetNextRunDate(RecurringTransaction__c objectRecurringTransaction)
	{
		string frequency = string.valueof(objectRecurringTransaction.No_of__c);
				
		if(objectRecurringTransaction.Last_Posted__c == null)		
			objectRecurringTransaction.Next_Transaction_Date__c = Date.today();		
		else
			objectRecurringTransaction.Next_Transaction_Date__c = objectRecurringTransaction.Last_Posted__c;		
		if(objectRecurringTransaction.Name_of__c == 'Day(s)')		
			objectRecurringTransaction.Next_Transaction_Date__c = objectRecurringTransaction.Next_Transaction_Date__c.addDays(integer.valueof(frequency));			
		if(objectRecurringTransaction.Name_of__c == 'Week(s)')		
			objectRecurringTransaction.Next_Transaction_Date__c = objectRecurringTransaction.Next_Transaction_Date__c.addDays(integer.valueof(frequency)*7);			
		if(objectRecurringTransaction.Name_of__c == 'Month(s)')		
			objectRecurringTransaction.Next_Transaction_Date__c = objectRecurringTransaction.Next_Transaction_Date__c.addMonths(integer.valueof(frequency));								
	}
}