ZumZumFinancials_Dev1/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Nominal_Account__c</fullName>
        <label>Nominal Account</label>
        <referenceTo>Nominal_Account__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Tax_Rate__c</fullName>
        <label>Tax Rate</label>
        <referenceTo>Tax_Rate__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

ZumZumFinancials_Dev1/src/objects/Invoice_Template__c.object
<CustomObject>
    <fields>
        <fullName>Font_Face__c</fullName>
        <label>Font Face</label>
        <picklist>
            <picklistValues>
                <fullName>Arial</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Times New Roman</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Verdana</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Font_Size__c</fullName>
        <label>Font Size</label>
        <picklist>
            <picklistValues>
                <fullName>1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>6</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>7</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>8</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>9</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>11</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>12</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>13</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>14</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>15</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>16</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>17</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>18</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>19</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Footer_Text__c</fullName>
        <label>Footer Text</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Heading_Text__c</fullName>
        <defaultValue>&quot;Invoice Heading&quot;</defaultValue>
        <label>Heading Text</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Is_Default__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Default</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Margins_left_right_Inches__c</fullName>
        <defaultValue>1.5</defaultValue>
        <label>Margins (left/right) - Inches</label>
        <precision>2</precision>
        <scale>1</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Margins_top_bottom__c</fullName>
        <defaultValue>1.5</defaultValue>
        <label>Margins (top/bottom) - Inches</label>
        <precision>2</precision>
        <scale>1</scale>
        <type>Number</type>
    </fields>
    <label>Invoice Template</label>
    <nameField>
        <label>Invoice Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Invoice Template</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

ZumZumFinancials_Dev1/src/objects/Nominal_Account__c.object
<CustomObject>
    <fields>
        <fullName>Account_Code__c</fullName>
        <label>Account Code</label>
        <precision>4</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>P_O__c</fullName>
        <defaultValue>false</defaultValue>
        <label>P O</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Sub_Category__c</fullName>
        <label>Sub Category</label>
        <referenceTo>Sub_Category__c</referenceTo>
        <relationshipLabel>Nominal Accounts</relationshipLabel>
        <relationshipName>Nominal_Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Tax_Rate__c</fullName>
        <label>Tax Rate</label>
        <referenceTo>Tax_Rate__c</referenceTo>
        <relationshipLabel>Nominal Accounts</relationshipLabel>
        <relationshipName>Nominal_Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Nominal Account</label>
    <nameField>
        <label>Nominal Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Nominal Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

ZumZumFinancials_Dev1/src/objects/Nominal_Categories__c.object
<CustomObject>
    <label>Nominal Category</label>
    <nameField>
        <label>Nominal Categories Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Nominal Categories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

ZumZumFinancials_Dev1/src/objects/Purchase_Order__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <label>Supplier Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Purchase Orders</relationshipLabel>
        <relationshipName>Purchase_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Approved_By__c</fullName>
        <label>Approved By</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Purchase_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Order_By__c</fullName>
        <label>Order By</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Purchase_Orders1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Order_Date__c</fullName>
        <label>Order Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Approval</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Goods Recieved</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Supplier_Reference__c</fullName>
        <label>Supplier Reference</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Total_Amount__c</fullName>
        <label>Total Amount</label>
        <summarizedField>Purchase_Order_Line_Items__c.Total_Amount__c</summarizedField>
        <summaryForeignKey>Purchase_Order_Line_Items__c.Purchase_Order__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Total_Gross__c</fullName>
        <label>Total Amount</label>
        <summarizedField>Purchase_Order_Line_Items__c.Total_Gross__c</summarizedField>
        <summaryForeignKey>Purchase_Order_Line_Items__c.Purchase_Order__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Total_Net__c</fullName>
        <label>Total Net</label>
        <summarizedField>Purchase_Order_Line_Items__c.Amount__c</summarizedField>
        <summaryForeignKey>Purchase_Order_Line_Items__c.Purchase_Order__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Total_VAT__c</fullName>
        <label>Total VAT</label>
        <summarizedField>Purchase_Order_Line_Items__c.Total_VAT__c</summarizedField>
        <summaryForeignKey>Purchase_Order_Line_Items__c.Purchase_Order__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <label>Purchase Order</label>
    <nameField>
        <label>Purchase Order Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Purchase Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

ZumZumFinancials_Dev1/src/objects/Purchase_Order_Line_Items__c.object
<CustomObject>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Item_Received__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Item Received</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Narrative__c</fullName>
        <label>Narrative</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Purchase Order Line Items (Opportunity)</relationshipLabel>
        <relationshipName>Purchase_Order_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Purchase Order Line Items</relationshipLabel>
        <relationshipName>Purchase_Order_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Purchase_Order__c</fullName>
        <label>Purchase Order</label>
        <referenceTo>Purchase_Order__c</referenceTo>
        <relationshipLabel>Purchase Order Line Items</relationshipLabel>
        <relationshipName>Purchase_Order_Line_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <label>Quantity</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Serial_No__c</fullName>
        <label>Serial No</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Tax_Rate__c</fullName>
        <label>Tax Rate</label>
        <referenceTo>Tax_Rate__c</referenceTo>
        <relationshipName>Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Total_Amount__c</fullName>
        <label>Total Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Total_Gross__c</fullName>
        <label>Total Amount</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Total_VAT__c</fullName>
        <label>Total VAT</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>UID__c</fullName>
        <displayFormat>PO# {000000}</displayFormat>
        <label>UID</label>
        <type>AutoNumber</type>
    </fields>
    <label>Purchase Order Line Items</label>
    <nameField>
        <label>Line Items Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Purchase Order Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

ZumZumFinancials_Dev1/src/objects/Sub_Category__c.object
<CustomObject>
    <fields>
        <fullName>Nominal_Categories__c</fullName>
        <label>Nominal Categories</label>
        <referenceTo>Nominal_Categories__c</referenceTo>
        <relationshipLabel>Sub Category</relationshipLabel>
        <relationshipName>Sub_Category</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Range_From__c</fullName>
        <label>Range From</label>
        <precision>4</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Range_To__c</fullName>
        <label>Range To</label>
        <precision>4</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Sub Category</label>
    <nameField>
        <label>Sub Category Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sub Category</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

ZumZumFinancials_Dev1/src/objects/Tax_Rate__c.object
<CustomObject>
    <fields>
        <fullName>Tax_Rate__c</fullName>
        <label>Tax Rate</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>is_default__c</fullName>
        <defaultValue>false</defaultValue>
        <label>is default</label>
        <type>Checkbox</type>
    </fields>
    <label>Tax</label>
    <nameField>
        <label>Tax Rate Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tax</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

ZumZumFinancials_Dev1/src/classes/PurchaseOrder_Pdf.cls
public class PurchaseOrder_Pdf 
{
	public Purchase_Order__c PurchaseOrderinfo {get; set;}
	public List<Purchase_Order_Line_Items__c> PoLineItems {get; set;} 
	public string UserName {get; set;}
	public string orderDate {get; set;}
	public decimal PoAmount {get;  set ; }
	public decimal totalTax {get; set;}
	public decimal wtAmount {get; set;}
	public boolean allowedit {get; set;}
	public decimal totalVat {get; set;}
	public decimal totalNetAmunt {get; set;}
	public boolean showPdf {get; set;}
	public List<POLineItemWrapper> Lineitems {get; set;}
	public string imageUrl {get; set;}
	public Invoice_Template__c invoiceTmpl {get; set;}
	public PurchaseOrder_Pdf( apexpages.Standardcontroller generatePdf )
	{
		//init();	
	}
	public PurchaseOrder_Pdf(  )
	{
		//init();	
	}
	public void init()
	{
		try
		{
			Id purchaseOrderId = apexpages.currentPage().getParameters().get('id');
			PurchaseOrderinfo  = [ Select p.CreatedBy.Name , p.Total_VAT__c, p.Total_Net__c, p.Total_Gross__c, p.Total_Amount__c, p.Supplier_Reference__c, p.Status__c, p.OwnerId, p.Order_Date__c, p.Order_By__c, p.Name, p.Id, p.Approved_By__c, p.Account__c From Purchase_Order__c p where p.Id = :purchaseOrderId limit 1];
			if (PurchaseOrderinfo.Status__c == 'Pending' || PurchaseOrderinfo.Status__c == 'Submitted_For_Approval' || PurchaseOrderinfo.Status__c == 'Rejected' )
			{
				showPdf =false;
				throw new CustomException(PurchaseOrderinfo.Name +' is not Approved, You Cannot View Purchase Order Pdf ');
			}
			List<Invoice_Template__c> invTmpl = [Select i.Footer_Text__c  , i.Name, i.Margins_top_bottom__c, i.Margins_left_right_Inches__c, i.Heading_Text__c, i.Font_Size__c, i.Font_Face__c From Invoice_Template__c i where Is_Default__c = true];
			if(invTmpl.size() == 0)
				throw new CustomException('No Default Template Found , Please select Template as default');
			else
				invoiceTmpl = invTmpl[0] ;
			List<Attachment> att = [Select a.ParentId, a.Name, a.Id, a.Description, a.ContentType, a.BodyLength, a.Body From Attachment a where a.ParentId = : invoiceTmpl.id  limit 1];
			if(att.size() > 0 )
				imageUrl = 'https://'+apexpages.currentPage().getHeaders().get('host').substring(0 ,apexpages.currentPage().getHeaders().get('host').indexOf('.',2))+'.content.force.com/servlet/servlet.FileDownload?file='+string.valueof(att[0].id) ;
			else
				throw new CustomException('No Invoice Logo Found for Default Template, Please Upload Logo for Default Template');
			showPdf = true ;
			orderDate = PurchaseOrderinfo.Order_Date__c.format();
			Lineitems = new List<POLineItemWrapper>();
			for (Purchase_Order_Line_Items__c poI : [Select p.UID__c, p.Total_Gross__c, p.Total_Amount__c, p.Tax_Rate__c, p.Tax_Rate__r.Tax_Rate__c,p.Total_VAT__c, p.Serial_No__c, p.Quantity__c, p.Purchase_Order__c, p.Product__c,p.Product__r.Name, p.Opportunity__c,p.Opportunity__r.Name, p.Narrative__c, p.Name, p.Item_Received__c, p.IsDeleted, p.Id, p.Amount__c From Purchase_Order_Line_Items__c p where p.Purchase_Order__c = :purchaseOrderId])
			{
				POLineItemWrapper tmwrap = new POLineItemWrapper(poI);
				tmwrap.serialNumber = Lineitems.size();
				tmwrap.taxRate = poI.Tax_Rate__r.Tax_Rate__c ;
				Lineitems.add(tmwrap);	
			}
		}
		catch(exception e)
		{
			apexpages.addMessages(e);	
		}
		
	}
	private static testmethod void Test_Purchase_Order_AddEditController()
	{
		//preparing data for unit testing
		Account act = new Account(Name='ABC Company',Type='Supplier');
		insert act;
		Tax_Rate__c tx = new Tax_Rate__c(Name = 'VAT' , Tax_Rate__c = 15 );
		insert tx ;
		Nominal_Categories__c  nc = new Nominal_Categories__c (Name = 'this is test');
		insert nc ; 
		Sub_Category__c sb = new Sub_Category__c(Nominal_Categories__c = nc.Id , Range_To__c = 200, Range_From__c=10, Name = 'testSubcatagories');
		insert sb;
		Nominal_Account__c nm = new Nominal_Account__c (Sub_Category__c = sb.Id , Tax_Rate__c = tx.Id, P_O__c = true, Name = 'Plumbering', Account_Code__c = 150);
		insert nm ;
		Purchase_Order__c Cont = new Purchase_Order__c(Name = '00050' , Account__c = act.Id  , Order_Date__c = date.today() , Status__c = 'Approved' , Order_By__c = userinfo.getUserId());
		insert Cont ;
		Purchase_Order_Line_Items__c tmpline = new Purchase_Order_Line_Items__c();
		tmpline.Serial_No__c = 1 ;
		tmpline.Amount__c = 20 ;
		tmpline.Total_Gross__c = 20 ;
		tmpline.Quantity__c = 1 ;
		tmpline.Narrative__c = 'item name' ;
		tmpline.Total_VAT__c = 0 ;
		//tmpline.Nominal_Account__c = nm.Id;
		tmpline.Tax_Rate__c = tx.id ;
		tmpline.Purchase_Order__c = Cont.id;
		insert tmpline ;
		//Purchase_Order__c Cont = [select Id from Purchase_Order__c limit 1];
		ApexPages.currentPage ().getParameters ().put ('deleteId', Cont.id);
		ApexPages.currentPage ().getParameters ().put ('id', Cont.id);    
        ApexPages.StandardController stdCon = new ApexPages.StandardController (Cont);
        PurchaseOrder_Pdf objj  = new PurchaseOrder_Pdf(stdCon);
        objj.init();
        Cont = new Purchase_Order__c(Name = '00050' , Account__c = act.Id  , Order_Date__c = date.today() , Status__c = 'Pending' , Order_By__c = userinfo.getUserId());
		insert Cont ;
		ApexPages.currentPage ().getParameters ().put ('id', Cont.id);
		try
		{
			objj.init();
		}
		catch (exception e)
		{
			system.assertEquals(Cont.Name +' is not Approved, You Cannot View Purchase Order Pdf ', e.getMessage());
		}
		ApexPages.currentPage ().getParameters ().put ('id', null );
		objj.init();
		
	}
}