ZumZumFinancials_Dev1/src/objects/Company_Setup__c.object
<CustomObject>
    <fields>
        <fullName>Account_Lock_Date__c</fullName>
        <label>Account Lock Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Company_Registration_Number__c</fullName>
        <label>Company Registration Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Entity_Type__c</fullName>
        <label>Entity Type</label>
        <picklist>
            <picklistValues>
                <fullName>Company</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sole trader</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Partnership</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>VAT_Number__c</fullName>
        <label>VAT Number</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>VatMethod__c</fullName>
        <label>VAT Method</label>
        <picklist>
            <picklistValues>
                <fullName>Cash Accounting</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Accrual</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Company Setup</label>
    <nameField>
        <label>Company Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Company Setup</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

ZumZumFinancials_Dev1/src/classes/CompanySetupController.cls
public class CompanySetupController {
	public Company_Setup__c cn {get;set;}
	public string cnId  {get;set;}
	public CompanySetupController(ApexPages.standardcontroller std)
	{
		cnId  = [select id from Company_Setup__c limit 1].id;
	}
	public PageReference init()
	{
		cn = [select id,Name, Account_Lock_Date__c, Company_Registration_Number__c,Entity_Type__c, VatMethod__c, VAT_Number__c from Company_Setup__c where id=: cnId ];
		return new PageReference('/'+cn.id);
	}	
	private static testMethod void CompanySetupController_Test()
	{
		CompanySetupController cs = new CompanySetupController(new ApexPages.standardController(new Company_Setup__c()));
		cs.init();
	} 
}