ZumZumFinancials_Dev1/src/objects/CurrencyField__c.object
<CustomObject>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>CurrencyField</label>
    <nameField>
        <label>CurrencyField Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CurrencyFields</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

ZumZumFinancials_Dev1/src/classes/NominalCategoryTotals.cls
public class NominalCategoryTotals
{
	public NominalCategoryTotals()
	{
		
	}
	
	public string Name {get; set;}
	public decimal PeriodTotal {get; set;}
	public decimal ToDateTotal {get; set;}
	public CurrencyField__c PeriodTotalCurrency
	{
		get
		{
			return new CurrencyField__c(Amount__c=PeriodTotal);
		}
	}
	public CurrencyField__c ToDateTotalCurrency
	{
		get
		{
			return new CurrencyField__c(Amount__c=ToDateTotal);
		}
	}
}