ZumZumFinancials_Dev1/src/objects/DataTypeHelper__c.object
<CustomObject>
    <fields>
        <fullName>Currency__c</fullName>
        <label>Currency</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>DataTypeHelper</label>
    <nameField>
        <label>DataTypeHelper Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DataTypeHelper</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

ZumZumFinancials_Dev1/src/objects/Ledger__c.object
<CustomObject>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount Paid</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Net__c</fullName>
        <formula>Credit__c  +  Debit__c  -  Tax__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Net</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Tax__c</fullName>
        <label>Tax</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Ledger</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Ledger Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ledger</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

ZumZumFinancials_Dev1/src/classes/LedgerEntry.cls
public class LedgerEntry
{
	public Ledger__c Entry {get;set;}
	public List<Ledger__c> PaymentDetails {get;set;}
	public DataTypeHelper__c AccountLookup {get;set;}
	
	public DataTypeHelper__c RemainingAmount
	{
		get
		{
			decimal netAmount = Entry.Net__c!=null ? Entry.Net__c : 0;
			decimal taxAmount = Entry.Tax__c!=null ? Entry.Tax__c : 0; 
			decimal paidAmount = Entry.Amount__c!=null ? Entry.Amount__c : 0; 
			return new DataTypeHelper__c(Currency__c=netAmount + taxAmount - paidAmount);
		}
	}
	public decimal Discount {get;set;}
	public decimal Receipt {get;set;}
	
	public LedgerEntry(Ledger__c e)
	{
		this.Entry = e;		
	}			
}