ZumZumFinancials_Dev1/src/objects/Ledger__c.object
<CustomObject>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount Paid</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Bank_Reconcile_Date__c</fullName>
        <label>Bank Reconcile Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Bank_Reconcile__c</fullName>
        <label>Bank Reconcile</label>
        <length>1</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Credit__c</fullName>
        <label>Credit</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Debit__c</fullName>
        <label>Debit</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Details__c</fullName>
        <label>Details</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Doc_ID__c</fullName>
        <label>Doc ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Nominal__c</fullName>
        <label>Nominal</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Paid__c</fullName>
        <label>Paid</label>
        <length>1</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Reference__c</fullName>
        <label>Reference</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Show_On_Transaction__c</fullName>
        <label>Show On Transaction</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Sub_Account_Nominal__c</fullName>
        <label>Sub Account Nominal</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sub_Account__c</fullName>
        <label>Sub Account</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Tax_Code__c</fullName>
        <label>Tax Code</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Tax__c</fullName>
        <label>Tax</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Trans_Date__c</fullName>
        <label>Trans Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Trans_Ref_Id__c</fullName>
        <label>Trans. Ref. Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>BP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>JC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>JD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SR</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>VAT_Return_Date__c</fullName>
        <label>VAT Return Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>VAT_Return_No__c</fullName>
        <label>VAT Return No.</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>VAT__c</fullName>
        <label>VAT</label>
        <length>1</length>
        <type>Text</type>
    </fields>
    <label>Ledger</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Ledger Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ledger</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

ZumZumFinancials_Dev1/src/classes/LedgerTransactionWrapper.cls
public class LedgerTransactionWrapper 
{
	public Decimal Amount {get;set;}
	public String BankReconcile {get;set;}
	public Date ReconcileDate {get;set;}
	public Decimal Credit {get;set;}
	public Decimal Debit {get;set;}
	public String Details {get;set;}
	public String Doc {get;set;}
	public String Nominal {get;set;}
	public String Paid {get;set;}
	public String Reference {get;set;}
	public Decimal ShowOnTransaction {get;set;}
	public String SubAccount {get;set;}
	public String SubAccountNominal {get;set;}
	public Decimal Tax {get;set;}
	public string TaxCode {get;set;}
	public Decimal TransNo {get;set;}
	public String TransRefId {get;set;}
	public Date TransDate {get;set;}
	public String TrType {get;set;}
	public String VAT {get;set;}
	public Date VATReturnDate {get;set;}
	public String VATReturnNo {get;set;}
	
	public LedgerTransactionWrapper()
	{
		
	}
	
	public LedgerTransactionWrapper(Ledger__c ledgerRecord)
	{
		this.Amount = ledgerRecord.Amount__c;
		this.BankReconcile = ledgerRecord.Bank_Reconcile__c;
		this.ReconcileDate = ledgerRecord.Bank_Reconcile_Date__c;
		this.Credit = ledgerRecord.Credit__c;
		this.Debit = ledgerRecord.Debit__c;
		this.Details = ledgerRecord.Details__c;
		this.Doc = ledgerRecord.Doc_ID__c;
		this.Nominal = ledgerRecord.Nominal__c;
		this.Paid = ledgerRecord.Paid__c;
		this.Reference = ledgerRecord.Reference__c;
		this.ShowOnTransaction = ledgerRecord.Show_On_Transaction__c;
		this.SubAccount = ledgerRecord.Sub_Account__c;
		this.SubAccountNominal = ledgerRecord.Sub_Account_Nominal__c; 
		this.Tax = ledgerRecord.Tax__c;
		this.TaxCode = ledgerRecord.Tax_Code__c;
		this.TransRefId = ledgerRecord.Trans_Ref_Id__c;
		this.TransDate = ledgerRecord.Trans_Date__c;
		this.TrType = ledgerRecord.Type__c;
		this.VAT = ledgerRecord.VAT__c;
		this.VATReturnDate = ledgerRecord.VAT_Return_Date__c;
		this.VATReturnNo = ledgerRecord.VAT_Return_No__c;
	}
}