ZumZumFinancials_Dev1/src/objects/Ledger__c.object
<CustomObject>
    <fields>
        <fullName>Bank_Reconcile_Date__c</fullName>
        <label>Bank Reconcile Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Is_Deleted__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Deleted</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Net__c</fullName>
        <formula>Credit__c  +  Debit__c  -  Tax__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Net</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Trans_Date__c</fullName>
        <label>Trans Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>BP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>JC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>JD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SR</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Ledger</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Ledger Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ledger</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

ZumZumFinancials_Dev1/src/classes/PurchaseReportController.cls
public class PurchaseReportController {
	public Ledger__c objectLedger {get;set;}
	public List<Ledger__c> listLedger {get;set;}	
	public PurchaseReportWrapper objectwrapper;
	public List<PurchaseReportWrapper> listwrapper;
	public integer mName;
	public integer yName;
	public decimal purchase;
	public decimal crdtNote;	
	public Date stDate;
	public string currencySymbol{get;set;}		
	public PurchaseReportController ()
	{
		objectLedger = new Ledger__c();		
		currencySymbol = Functions.getOrganisationCurrency('CurrencySymbol');				 
	}
	public void CalculateforExcel()
	{
		try
		{			
			objectLedger.Trans_Date__c = Date.parse(apexpages.currentPage().getParameters().get('StartDate'));
			objectLedger.Bank_Reconcile_Date__c = Date.parse(apexpages.currentPage().getParameters().get('EndDate'));		
			Calculate();
		}
		catch(exception e) 
		{
			apexpages.addmessages(e);
		}				
	}
	public void Calculate()
	{
		try
		{			
			validationRules();					
			listLedger = [Select Type__c, Net__c , Trans_Date__c  From Ledger__c  where Trans_Date__c >=: objectLedger.Trans_Date__c and Trans_Date__c <=: objectLedger.Bank_Reconcile_Date__c and Is_Deleted__c = false];									
			listwrapper = new List<PurchaseReportWrapper>();
			stDate = objectLedger.Trans_Date__c;											
			do
			{			
				mName = stDate.Month();
				yName = stDate.Year();	
				purchase = 0.0;
				crdtNote = 0.0;
				for(Ledger__c ld : listLedger)
				{					
					if((ld.Trans_Date__c.Month() == mName) && (ld.Trans_Date__c.Year() == yName))
					{
						if((ld.Type__c == 'PI'))
						{	
							purchase = purchase + ld.Net__c; 												
						}
						else if((ld.Type__c == 'PC'))
						{	
							crdtNote = crdtNote + ld.Net__c ;
						}
					}
				}
				objectwrapper = new PurchaseReportWrapper(stDate , purchase , crdtNote);								
				listwrapper.add(objectwrapper);
				stDate = stDate.addMonths(1);					
			}
			while(stDate <= objectLedger.Bank_Reconcile_Date__c);
		}
		catch(exception e)
		{
			apexpages.addmessages(e);
		}
	}	
	public List<PurchaseReportWrapper> getPurchaseReport()
	{		
		return listwrapper;	
	}
	public void validationRules()
	{
		if(objectLedger.Trans_Date__c == null)		
			throw new CustomException('Enter From Date first');
		if(objectLedger.Bank_Reconcile_Date__c == null)		
			throw new CustomException('Enter To Date first');
	}
	private static testMethod void PurchaseReportController_Test()
	{
		Ledger__c ldg = new Ledger__c(Trans_Date__c = Date.newInstance(2011,1,1) , Bank_Reconcile_Date__c = Date.today());
		insert ldg;
		PurchaseReportController pRpt = new PurchaseReportController();
		try
		{
			pRpt.ValidationRules();
		}
		catch(exception e)
		{
			system.assertEquals(e.getMessage(),'Enter From Date first');
		}
		pRpt.objectLedger.Trans_Date__c = ldg.Trans_Date__c;
		try
		{
			pRpt.ValidationRules();
		}
		catch(exception e)
		{
			system.assertEquals(e.getMessage(),'Enter To Date first');
		}
		pRpt.objectLedger.Bank_Reconcile_Date__c = ldg.Bank_Reconcile_Date__c;				
		pRpt.Calculate();
		List<PurchaseReportWrapper> prw = pRpt.getPurchaseReport();
		pRpt.CalculateforExcel();	
	}
}