ZumZumFinancials_Dev1/src/objects/Nominal_Account__c.object
<CustomObject>
    <fields>
        <fullName>Account_Code__c</fullName>
        <label>Account Code</label>
        <precision>4</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Expense__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Expense</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Nominal_Code__c</fullName>
        <formula>TEXT( Account_Code__c )</formula>
        <label>Nominal Code</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sub_Category__c</fullName>
        <label>Sub Category</label>
        <referenceTo>Sub_Category__c</referenceTo>
        <relationshipLabel>Nominal Accounts</relationshipLabel>
        <relationshipName>Nominal_Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Tax_Rate__c</fullName>
        <label>Tax Rate</label>
        <referenceTo>Tax_Rate__c</referenceTo>
        <relationshipLabel>Nominal Accounts</relationshipLabel>
        <relationshipName>Nominal_Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Nominal Account</label>
    <nameField>
        <label>Nominal Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Nominal Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

ZumZumFinancials_Dev1/src/objects/Nominal_Categories__c.object
<CustomObject>
    <label>Nominal Category</label>
    <nameField>
        <label>Nominal Categories Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Nominal Categories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

ZumZumFinancials_Dev1/src/objects/Sub_Category__c.object
<CustomObject>
    <fields>
        <fullName>Nominal_Categories__c</fullName>
        <label>Nominal Categories</label>
        <referenceTo>Nominal_Categories__c</referenceTo>
        <relationshipLabel>Sub Category</relationshipLabel>
        <relationshipName>Sub_Category</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Range_From__c</fullName>
        <label>Range From</label>
        <precision>4</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Range_To__c</fullName>
        <label>Range To</label>
        <precision>4</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Sub Category</label>
    <nameField>
        <label>Sub Category Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sub Category</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

ZumZumFinancials_Dev1/src/objects/Tax_Rate__c.object
<CustomObject>
    <fields>
        <fullName>Tax_Rate__c</fullName>
        <label>Tax Rate</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <label>Tax</label>
    <nameField>
        <label>Tax Rate Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tax</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

ZumZumFinancials_Dev1/src/classes/NominalActivityController.cls
public class NominalActivityController {		
	public string NomId{get;set;}
	public Report rpt {get;set;}	
	public Nominal_Account__c Nominal{get;set;}	
	public NominalActivityController(ApexPages.StandardController std)
	{				
		NomId = ApexPages.currentPage().getParameters().get('Id');
		system.debug('id is : '+NomId);		
		if(NomId != null && NomId != '')
			Nominal = [select id, Name, Nominal_Code__c from Nominal_Account__c where id =: NomId];
		system.debug('object is : '+Nominal);							
	}
	public pagereference NominalAction()
	{		
		rpt = [select id , DeveloperName , Name from Report where DeveloperName = 'Nominal_Activity2'];
		system.debug('report is : '+rpt);
		return new pageReference('/'+rpt.id+'?pv0='+Nominal.Nominal_Code__c);
	}
	private static testMethod void NominalActivityController_Test()
	{
		Tax_Rate__c tx = new Tax_Rate__c(Name = 'VAT' , Tax_Rate__c = 15 );
		insert tx ;
    	Nominal_Categories__c  nc = new Nominal_Categories__c (Name = 'this is test');
		insert nc ; 
		Sub_Category__c sb = new Sub_Category__c(Nominal_Categories__c = nc.Id , Range_To__c = 200, Range_From__c=10, Name = 'testSubcatagories');
		insert sb;
		Nominal_Account__c nm = new Nominal_Account__c (Sub_Category__c = sb.Id , Tax_Rate__c = tx.Id, Expense__c = true, Name = 'Plumbering', Account_Code__c = 1222);
		insert nm ;
		ApexPages.currentPage().getParameters().put('Id',nm.id);
		NominalActivityController nActvty = new NominalActivityController(new ApexPages.StandardController(new Nominal_Account__c()));
		nActvty.NominalAction();		
	} 
}