ZumZumFinancials_Dev1/src/objects/Nominal_Account__c.object
<CustomObject>
    <fields>
        <fullName>Sub_Category__c</fullName>
        <label>Sub Category</label>
        <referenceTo>Sub_Category__c</referenceTo>
        <relationshipLabel>Nominal Accounts</relationshipLabel>
        <relationshipName>Nominal_Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Nominal Account</label>
    <nameField>
        <label>Nominal Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Nominal Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

ZumZumFinancials_Dev1/src/objects/Nominal_Budget__c.object
<CustomObject>
    <fields>
        <fullName>Actuals_Credit__c</fullName>
        <label>Actuals_Credit</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Actuals_Debit__c</fullName>
        <label>Actuals_Debit</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Month__c</fullName>
        <label>Month</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Nominal_Account__c</fullName>
        <label>Nominal Account</label>
        <referenceTo>Nominal_Account__c</referenceTo>
        <relationshipLabel>Nominal Budgets</relationshipLabel>
        <relationshipName>Nominal_Budgets</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Year__c</fullName>
        <label>Year</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Nominal Budget</label>
    <nameField>
        <label>Nominal Budget Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Nominal Budgets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

ZumZumFinancials_Dev1/src/objects/Nominal_Categories__c.object
<CustomObject>
    <label>Nominal Category</label>
    <nameField>
        <label>Nominal Categories Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Nominal Categories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

ZumZumFinancials_Dev1/src/objects/Sub_Category__c.object
<CustomObject>
    <fields>
        <fullName>Nominal_Categories__c</fullName>
        <label>Nominal Categories</label>
        <referenceTo>Nominal_Categories__c</referenceTo>
        <relationshipLabel>Sub Category</relationshipLabel>
        <relationshipName>Sub_Category</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Sub Category</label>
    <nameField>
        <label>Sub Category Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sub Category</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

ZumZumFinancials_Dev1/src/classes/ReportControllerBase.cls
public abstract class ReportControllerBase
{
	protected AggregateResult[] QuerySubCatTotals(string mainCategoryName, integer startMonth, integer startYear, integer endMonth, integer endYear)
	{
		//apexpages.addmessage(new apexpages.message(apexpages.severity.info,'mainCategoryName: '+mainCategoryName+' - startMonth: '+startMonth+'  - startYear: '+startYear+' - endMonth: '+endMonth+' - endYear: '+endYear));
		return [Select n.Nominal_Account__r.Sub_Category__c subCategoryId, n.Nominal_Account__r.Sub_Category__r.Name subCategoryName, Sum(n.Actuals_Debit__c) totalDebit, Sum(n.Actuals_Credit__c) totalCredit 
			    From Nominal_Budget__c n
			    Where n.Nominal_Account__r.Sub_Category__r.Nominal_Categories__r.Name=:mainCategoryName
			    and ((Month__c>=:startMonth and Year__c>=:startYear) or (Month__c<=:endMonth and Year__c<=:endYear))
			    Group by n.Nominal_Account__r.Sub_Category__c, n.Nominal_Account__r.Sub_Category__r.Name
			    Order by n.Nominal_Account__r.Sub_Category__r.Name];
	}
}