ZumZumFinancials_Dev1/src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Sub_Project__c</fullName>
        <label>Project</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Sub Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

ZumZumFinancials_Dev1/src/objects/Sales_Order_Line_Items__c.object
<CustomObject>
    <fields>
        <fullName>Product__c</fullName>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Sales Order Line Items</relationshipLabel>
        <relationshipName>Sales_Order_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Sales Order Line Items</relationshipLabel>
        <relationshipName>Sales_Order_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Total_Amount__c</fullName>
        <label>Total Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Total_Net__c</fullName>
        <label>Total Net</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>VAT_Amount__c</fullName>
        <label>VAT Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Sales Order Line Items</label>
    <nameField>
        <label>Sales Order Line Items Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Order Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

ZumZumFinancials_Dev1/src/classes/SOLineItemWrapper.cls
public class SOLineItemWrapper 
{
	public Sales_Order_Line_Items__c salesOrderLineItems {get; set;}
	public boolean taxselected {get; set;} 
	public integer serialNumber {get; set;}
	public decimal taxRate  {get; set;}
	public SOLineItemWrapper(Sales_Order_Line_Items__c soLineItems)
	{
		salesOrderLineItems = new Sales_Order_Line_Items__c();
		salesOrderLineItems = soLineItems ;	
		taxselected = false ;	
	}
	/*
	public List<selectoption> SubProjectList
	{
		get
		{
			list<selectoption> subProjectlist = new list<selectoption>();
			for (Opportunity op: [select Id, Name from Opportunity where Sub_Project__c = :salesOrderLineItems.Project__c AND Sub_Project__c != null Order By Name Asc limit 1000])
			{
				subProjectlist.add(new selectoption (op.Id , op.Name  ));	
			}
			if (SubProjectList.size() == 0)
			{
				SubProjectList.add(new selectoption('' , 'Select Sub Project'));
			}
			return subProjectlist ;
		}
		set;
	}
	*/
	public string totalTax
	{
		get
		{
			if (salesOrderLineItems.VAT_Amount__c ==null || salesOrderLineItems.VAT_Amount__c == 0)
			{
				return '0.00';
			}
			else
			{
				return string.valueof(salesOrderLineItems.VAT_Amount__c.setScale(2));
			}
		}
	}
	public string totalNet
	{
		get
		{
			if (salesOrderLineItems.Total_Net__c ==null || salesOrderLineItems.Total_Net__c == 0)
			{
				return '0.00';
			}
			else
			{
				return string.valueof(salesOrderLineItems.Total_Net__c.setScale(2));
			}
		}
	}
	public string totalAmount
	{
		get
		{
			if (salesOrderLineItems.Total_Amount__c ==null || salesOrderLineItems.Total_Amount__c == 0)
			{
				return '0.00';
			}
			else
			{
				return string.valueof(salesOrderLineItems.Total_Amount__c.setScale(2));
			}
		}
	}
	public string ProducName
	{
		get
		{
			if (salesOrderLineItems.Product__c !=null)
			{
				if (AllProductsMap.keyset().contains(salesOrderLineItems.Product__c) )
					return AllProductsMap.get(salesOrderLineItems.Product__c).ProductCode + ' - ' + AllProductsMap.get(salesOrderLineItems.Product__c).Name ;
				else if (!AllProductsMap.keyset().contains(salesOrderLineItems.Product__c) )
				{
					Product2 Product = [Select p.ProductCode, p.Name From Product2 p where Id = : salesOrderLineItems.Product__c];
					return Product.ProductCode + ' - ' + Product.Name ;
				}
				else
					return null;
			}
			else
				return null; 	
		}
		set;
	}
	public static map<Id , Product2> AllProductsMap = new map<Id , Product2>([Select p.ProductCode, p.Name From Product2 p where p.IsActive = true]);
	public string OppName
	{
		get
		{
			if (salesOrderLineItems.Project__c != null )
			{
				if (ALLOpportunities.keyset().contains(salesOrderLineItems.Project__c))
					return  ALLOpportunities.get(salesOrderLineItems.Project__c).Name ;
				else if(!ALLOpportunities.keyset().contains(salesOrderLineItems.Project__c))
				{
					Opportunity Opp = [Select o.StageName, o.Name, o.Id From Opportunity o where Id =:salesOrderLineItems.Project__c ];
					return Opp.Name ;
				}
				else
					return null ;
			}
			else
				return null; 	
		}
		set;
	}
	public static map<Id , Opportunity> ALLOpportunities = new map<Id , Opportunity>([Select o.StageName, o.Name, o.Id From Opportunity o where StageName  != 'Closed Won' and  StageName != 'Closed Lost']);
	
}