ZumZumFinancials_Dev1/src/objects/Time_Sheet__c.object
<CustomObject>
    <fields>
        <fullName>Month__c</fullName>
        <defaultValue>MONTH( TODAY() )</defaultValue>
        <label>Month</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Pending</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Year__c</fullName>
        <defaultValue>YEAR( TODAY() )</defaultValue>
        <label>Year</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Time Sheet</label>
    <nameField>
        <label>Time Sheet Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Time Sheets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

ZumZumFinancials_Dev1/src/classes/DeleteTimeSheet.cls
public class DeleteTimeSheet 
{
	public boolean disableDelete {get; set;}
	private id deleteId {get; set;}
	public DeleteTimeSheet( apexpages.Standardcontroller deleteTimeSheet )
	{
		deleteId = apexpages.currentPage().getParameters().get('delId');
		apexpages.addMessage(new apexpages.Message( apexpages.Severity.info , 'Are you Sure to Delete this Time Sheet?', '' ) );  
		disableDelete = true ;
	}
	public DeleteTimeSheet( )
	{
	
	}
	public pagereference init()
	{
		Savepoint sp = Database.setsavepoint(); 
		try
		{
			Time_Sheet__c ts = [select Id , Status__c , Name from Time_Sheet__c where Id =:deleteId];
			if ( ts.Status__c == 'Submitted_For_Approval' || ts.Status__c == 'Approved')
			{
				disableDelete = false ;
				throw new CustomException('Time Sheet TS#' + ts.Name + ' is ' + ts.Status__c + ' Its can\'t Be Deleted' );
				return null ;
			}
			else 
			{
				delete ts;
				return new pagereference ( '/' + apexpages.currentPage().getParameters().get('retURL') );	
			}
		}
		catch (exception e )
		{
			Database.rollback(sp);
			apexpages.addMessages(e);
			return null ;
		} 
	}
	public pagereference back()	
	{
		return new pagereference ('/' + deleteId );
	}
	public static testMethod void deleteTimeSheet()
	{
		Time_Sheet__c tsinfo = new Time_Sheet__c();
		tsinfo.Month__c = date.today().month();
		tsinfo.Year__c = date.today().year();
		tsinfo.Status__c = 'Pending';
		insert tsinfo ;
		ApexPages.currentPage().getParameters ().put ('delId', tsinfo.id);
		DeleteTimeSheet obj  = new DeleteTimeSheet();
		obj.init();
		tsinfo = new Time_Sheet__c();
		tsinfo.Month__c = date.today().month();
		tsinfo.Year__c = date.today().year();
		tsinfo.Status__c = 'Submitted_For_Approval';
		insert tsinfo ;
		ApexPages.currentPage().getParameters ().put ('delId', tsinfo.id);
		try
		{
			obj.init();	
		}
		catch(exception e)
		{
			system.assertEquals('Time Sheet TS#' + tsinfo.Name + ' is ' + tsinfo.Status__c + ' Its can\'t Be Deleted', e.getMessage());
		}
		ApexPages.currentPage().getParameters ().put ('delId', null );
		obj.init();	
		obj.back();
	}
}